### ISSUE TITLE
Contract deployment issue on a dev chain with 0 confirmation

### ISSUE THREAD

**Issue by cheme** [tomusdrw/rust-web3#109]
While testing parity bridge with nightly version (ok with 1.9.5). The deployment of contract with rust-web3 is stuck on confirmation wait. I believe it might be related with instant sealing running before and no block creation afterward. This kind of modification let me run it : https://github.com/cheme/rust-web3/commit/8af0f344ee2795167c79d58703d9955f8edc163c

I think it is a corner case (dev and no confirmation), but I still open this issue for information.
For reference : https://github.com/paritytech/parity-bridge/pull/151

**Comment by tomusdrw** [comment]
Resolved via #110
