### ISSUE TITLE
make block number U256 everywhere

### ISSUE THREAD

**Issue by snd** [tomusdrw/rust-web3#114]
block number is `U256` everywhere (https://tomusdrw.github.io/rust-web3/web3/types/enum.BlockNumber.html?search=block_number) except for `BlockNumber::Number(u64)` (https://tomusdrw.github.io/rust-web3/web3/types/enum.BlockNumber.html) where it's a `u64`. i think it would be good to have this consistent. if this is a change that's wanted i'll open a PR.

**Comment by tomusdrw** [comment]
Yeah, I think the spec say it should always be `Quantity` (not 100% sure about input parameters though), and we should probably use `U64` since it's more than enough for the block number (probably we haven't used it in the past due to lack of this type).

**Comment by snd** [comment]
by `U64` you mean the `U64` in ethereum-types, right?
what's the advantage this type has over `u64`?

right, `64` bits is big enough for the block number

**Comment by tomusdrw** [comment]
`U64` is JSON (de)serializable to hex and not just number.

**Comment by tomusdrw** [comment]
Done, we switched to `U128`.
