### ISSUE TITLE
Topic filter conversion.

### ISSUE THREAD

**Issue by afck** [tomusdrw/rust-web3#119]
Would it make sense to add this conversion?

```rust
impl From<ethabi::TopicFilter> for web3::types::FilterBuilder
```

Or possibly rather a `FilterBuilder` method?

```rust
pub fn topic_filter(self, topic_filter: ethabi::TopicFilter) -> Self
```

At least [poa-bridge](https://github.com/poanetwork/poa-bridge/blob/cdb79b9ba72bc7094ab7e03b133d4e03a1b5d48a/bridge/src/util.rs#L14) and [poa-ballot-stats](https://github.com/poanetwork/poa-ballot-stats/blob/d77c1edcd04d480b59b1bc72b47ec9275b7b49a3/src/util.rs#L62) currently manually implement this.

If you agree, I'm happy to open a PR.

**Comment by tomusdrw** [comment]
makes sense, we should try to integrate `ethabi` more tightly

**Comment by afck** [comment]
I'm happy to open a PR; I'd just need to know how to handle [rustfmt and CI](https://github.com/tomusdrw/rust-web3/issues/125) (whether to use stable or a particular nightly, etc.).
