### ISSUE TITLE
error calling existing contract

### ISSUE THREAD

**Issue by akosenkov** [tomusdrw/rust-web3#121]
Great project! (really missing on some complex examples that work with strings and dictionaries though)

I'm trying to get this simple example to work but it works only when deploying contract straight away or when I exclude the dictionary from the smart contract :(

```
Error message:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Invalid character 'x' at position 1', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

solc, the solidity compiler commandline interface
Version: 0.4.23+commit.124ca40d.Darwin.appleclang

```
[package]
name = "web3"
version = "0.1.0"
authors = ["Alex Kosenkov <alex.kosenkov@gmail.com>"]

[dependencies]
ethereum-types = "0.3"
web3 = "0.3.0"
rustc-hex = "1.0.0"
tokio-core = "0.1.17"
```

SimpleStorage.sol:
```
pragma solidity 0.4;

contract SimpleStorage {
    mapping(address => uint) public registry;
    function set(uint x) public {
        registry[msg.sender] = x;
    }
    function get(address device) public constant returns (uint) {
        return registry[device];
    }
}
```
main.rs:
```
extern crate rustc_hex;
extern crate web3;

use web3::futures::Future;
use web3::contract::{Contract, Options};
use web3::types::{Address, U256 };
use rustc_hex::{FromHex, ToHex};
use std::time;

fn deploy(net: &web3::Web3<web3::transports::Http>, coinbase: &Address) -> Address {
    let bytecode: Vec<u8> = include_str!("./build/SimpleStorage.bin")
        .from_hex()
        .unwrap();
    let contract = Contract::deploy(net.eth(), include_bytes!("./build/SimpleStorage.abi"))
        .unwrap()
        .confirmations(0)
        .poll_interval(time::Duration::from_secs(10))
        .options(Options::with(|opt| {
            opt.gas = Some(3_000_000.into())
        }))
        .execute(bytecode, (), *coinbase)
        .unwrap()
        .wait()
        .unwrap();
    println!("Deployed to: 0x{}", contract.address().to_hex());
    contract.address()
}

fn get_balance(net: &web3::Web3<web3::transports::Http>, coinbase: &Address) {
    println!("Primary account: 0x{}", coinbase.to_hex());
    let balance = net.eth().balance(*coinbase, None).wait().unwrap();
    println!("Balance: {}", balance);
}

fn main() {
    let (_eloop, transport) = web3::transports::Http::new("http://localhost:8545").unwrap();
    let web3 = web3::Web3::new(transport);
    let accounts = web3.eth().accounts().wait().unwrap();
    get_balance(&web3, &accounts[0]);

    let contract_addr = deploy(&web3, &accounts[0]);
    //let contract_addr: Address = "0xd12268704fee5d1111c80f83de03d88ef1700161".parse().unwrap();

    let contract = Contract::from_json(web3.eth(), contract_addr, include_bytes!("./build/SimpleStorage.abi")).unwrap();

    let result = contract.query("get", (accounts[0]), None, Options::default(), None);
    let storage: U256 = result.wait().unwrap();
    println!("{}", storage);

    contract.call("set", (23,), accounts[0], Options::default());

    let result = contract.query("get", (accounts[0]), None, Options::default(), None);
    let storage: U256 = result.wait().unwrap();
    println!("{}", storage);
}
```

Now if I record the output contract address and put it into the commented line (instead of calling deploy) - I see the error message as described...

Edit:
Ok, I get it, I had to remove '0x' from the address.
Yet I haven't seen an error until it gets into contract.query :(
Why is it a requirement to always remove 0x from the string?
And amazingly it worked despite that (until I started to use dictionary within the smart contract)...

**Comment by akosenkov** [comment]
Ok, I get it, I had to remove '0x' from the address for some reason.
Yet I haven't seen an error until it gets into contract.query :(

Why is it a requirement to always remove 0x from the string?

**Comment by akosenkov** [comment]
And amazingly it worked despite that until I started to use dictionary within the smart contract :)

**Comment by akosenkov** [comment]
Sorry for the formatting though T_T

**Comment by tomusdrw** [comment]
Sorry for a late response, can you elaborate what address you mean?

`Contract::from_json` will return error only if the ABI is invalid, we don't try to "connect" to the contract yet, only when you query the contract we use it's addresss and parameters and then check if it succeeded or not.

A log output of running parity node with `-lrpc=trace` will also help debug a bit. If you include `env_logger` in your project please run with `RUST_LOG=web3=trace` as well, to get some details of what kind of queries your project is making.

PRs to improve examples always welcome :)

**Comment by tomusdrw** [comment]
Seems it's resolved. Please reopen otherwise.
