### ISSUE TITLE
Figure out what's wrong with rustfmt during builds

### ISSUE THREAD

**Issue by tomusdrw** [tomusdrw/rust-web3#125]

**Comment by afck** [comment]
Is this related to the 0.7.0 update? It's probably best to fix a particular Rust nightly version; since rustfmt is managed by rustup as part of a toolchain now, that will pin the rustfmt version, too.
See https://github.com/tomusdrw/rust-web3/pull/124#issuecomment-390977481

**Comment by tomusdrw** [comment]
@afck I see, makes sense to me. I will try to fix to some working nightly version in #127

**Comment by tomusdrw** [comment]
Works now.
