### ISSUE TITLE
State modifying method call example

### ISSUE THREAD

**Issue by fredfortier** [tomusdrw/rust-web3#133]
The examples in this project have been invaluable to me. But they don't show me how to call payable, or any state modifying, methods of a contract. I know how to call a view method with `query` but it uses `Option::default()` in the `options` argument. I don't know how this translates to `call` which require specific options (gas, value, etc). I see the Options Struct in the doc but its usage is not obvious to me.

If you give me some rough guidelines, I'll create a full example and push a PR.

**Comment by fredfortier** [comment]
I'll figured it out. I'll push an example shortly.

**Comment by WyseNynja** [comment]
Did this example ever get written?
