### ISSUE TITLE
Question: EthFilter behavior on block-reorg

### ISSUE THREAD

**Issue by adklempner** [tomusdrw/rust-web3#142]
I was hoping to get some clarification on how filters created through `EthFilter.create_logs_filter` behave in the case of a block reorg.

When a reorg happens, will the filter reproduce any affected `Logs` with updated [`removed`](https://tomusdrw.github.io/rust-web3/web3/types/struct.Log.html#structfield.removed) and `log_type` values? This is the behavior documented in the source code for geth's [api](https://github.com/ethereum/go-ethereum/blob/953b5ac015da7fdef39c6864bb0cb490ffaa7959/eth/filters/api.go#L285), I'm wondering if this is true for Parity as well? (I know both use `eth_newFilter`, but the documentation for JSON RPC doesn't explicitly describe the same behavior as geth)

**Comment by adklempner** [comment]
Additionally, is there a way to test this behavior? Either with Parity or using a `TestTransport`?

**Comment by tomusdrw** [comment]
The behaviour is indeed client-dependent. Parity does not inform about removed/retracted logs, you might get a notification for the same log twice in case it got included in a chain that re-orged later on.

The Pub/Sub logs filter however does return `removed` logs in both Geth and Parity.

**Comment by tomusdrw** [comment]
Seems resolved.
