### ISSUE TITLE
The documentation doesn't match latest version

### ISSUE THREAD

**Issue by elichai** [tomusdrw/rust-web3#143]
Hi, the docs here: https://tomusdrw.github.io/rust-web3/web3/index.html are for master. and there's stuff exist there that doesn't exist in the latest `0.3.0` version.
I would like to know if you're planning to release a new version that will match the docs (I want to use the `web3.eth.logs` function)

**Comment by Isan-Rivkin** [comment]
Same problem

**Comment by tomusdrw** [comment]
New version released: https://github.com/tomusdrw/rust-web3/releases/tag/v0.3.1
Remember that you can always reference the github version in your `Cargo.toml` (you just won't be able to release your library to crates.io)
