### ISSUE TITLE
Migrate from tokio_core

### ISSUE THREAD

**Issue by insipx** [tomusdrw/rust-web3#146]
any plans to migrate to `tokio` from `tokio_core` in the near-future? I haven't looked through the entire codebase yet, but it seems as if it may be a sizeable undertaking

**Comment by debris** [comment]
I'd say that there are no plans to do it yet, as `tokio` seems to be very unstable.

**Comment by botika** [comment]
Do not you think to upgrade to tokyo? Actix and hyper is working. If stability is not a problem, you have planned to migrate it.

 Do you need help to migrate it?

**Comment by botika** [comment]
Seriously, I need to integrate it with the actix runtime. 

What are you going to do?

Please make clear what you are going to do about it

**Comment by tomusdrw** [comment]
@botika we currently use the library in a large codebase that is not migrating to `tokio=0.1` any time soon, so it's currently not a priority for us.

However I'm happy to fork of the `futures=0.1` based version and accept a PR to migrate `master` to `tokio=0.1`.

**Comment by botika** [comment]
Perfect, I'll get to it.

**Comment by WyseNynja** [comment]
Any progress on this @botika? I'm about to start a project and was planning to use async/await. There's compatibility layers, but I'd like to use as little of that as possible.

**Comment by barollet** [comment]
Hi do you have any news on tokio migration from tokio_core ?

**Comment by botika** [comment]
I could not make any progress, I spent 2 months in jail, you know "Arriba España!", and lost the job and with it, the interest in this project. Sorry!!

Thanks for your work

**Comment by WyseNynja** [comment]
Related: https://docs.rs/ethcontract/0.5.0/ethcontract/ 
> This crate is using std::future::Future for futures by wrapping web3 futures 0.1 with futures 0.3 compatibility layer. This means that this crate is ready for async/await!

**Comment by tomusdrw** [comment]
This should be done now.
