### ISSUE TITLE
Question: How to handle connection error

### ISSUE THREAD

**Issue by eduardonunesp** [tomusdrw/rust-web3#167]
How to properly handle connection error, in the following example I want to inform user about an error without show a "developer" string error

What I'm doing: 

```rust
    let (_eloop, transport) = match web3::transports::Http::new("http://localhost:7545") {
        Ok((l, t)) => (l, t),
        Err(err) => {
            println!("Cannot connect due a connection an error");
            std::process::exit(-1);
        }
    };
```

Corrently what happens is the error on terminal:

```
Error(Transport("Io(Os { code: 61, kind: ConnectionRefused, message: \"Connection refused\" })"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
```

I'd like to show 

```
Cannot connect due a connection an error
```

**Comment by tomusdrw** [comment]
@eduardonunesp HTTP transport doesn't require connection to be established. First request that you are making will just fail if the server is not available. I suspect that the error is returned by first call that you are making not in the snippet that you've shown.

**Comment by eduardonunesp** [comment]
That's `true` @tomusdrw, how stupid I was lol, that makes sense :)
