### ISSUE TITLE
Error(Abi(InvalidData) on query

### ISSUE THREAD

**Issue by tritone11** [tomusdrw/rust-web3#176]
I keep getting 
```
thread 'main' panicked at 'FAILED: Error(Abi(InvalidData), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })', src/libcore/result.rs:1009:5
```
I checked with eth_getCode if the contract exists, but still I cannot manage to query it  
This is my call
```
let result = JOB_CONTRACT.query("registerJob",(bytes_jobid,ethabi::Token::Int(max_workers)),accounts[1],opt,None).wait();
let res: U256 = result.expect("FAILED");
```

**Comment by tomusdrw** [comment]
Can you provide RPC logs from the backend or from web3? Would be awesome to see what actual RPC requests are made to the server.

**Comment by jordipainan** [comment]
use H256 types ! We solved by this way the same error

**Comment by CPerezz** [comment]
Just use H256 Struct to transfer the Bytes dataType:
https://docs.rs/ethereum-types/0.4.0/ethereum_types/struct.H256.html

**Comment by tritone11** [comment]
Many thanks!
