### ISSUE TITLE
warning: use of deprecated item 'ethereum_types::H256::from_slice': unconventional API, replaced by `new_from_slice` in version 0.3

### ISSUE THREAD

**Issue by harishbm34** [tomusdrw/rust-web3#177]
How to resolve this warning ?

**I have been using the latest version of the "web3 = "0.5.1" in Cargo.toml.**

If I use, "git" path for web3 in the Cargo.toml (web3 = { git = "https://github.com/tomusdrw/rust-web3" }), getting the errors like below:

 --> /Users/harisha/.cargo/git/checkouts/rust-web3-ebc1a09fd5a9a2a2/8a2cfff/src/types/traces.rs:4:20
  |
4 | use serde_derive::{Deserialize, Serialize};
  |                    ^^^^^^^^^^^ no `Deserialize` in the root. Did you mean to use `Serialize`?

**Comment by tomusdrw** [comment]
@harishbm34 please update your Rust compiler, to fix `serde_derive` imports.
Regarding the warning, can you please post your `Cargo.lock` file? I'm not sure how you can get this warning, cause `from_slice` is not realy present in the codebase afaict.

**Comment by harishbm34** [comment]
Yes, after updating the Rust compiler I am not getting any error but still I can see the warnings.

Request you to please help me to fix this. 

Please find the attachment for the Cargo.lock file : 
[Cargo_lock.txt](https://github.com/tomusdrw/rust-web3/files/2666997/Cargo_lock.txt)

**Comment by tomusdrw** [comment]
Seems that `sputnikvm-precompiled-interchaintrx` crate is using `ethereum-types` as well, are you sure there are no occurences of `::from_slice` there?

That said: the warnings are currently not fixable (see https://github.com/paritytech/parity-common/issues/90). You need to bump `fixed-hash` to `0.3`, but it requires bumping all crates depending on `fixed-hash`. The main one would be `ethereum-types`, which is already updated in the repo, but not yet released on crates.io.
We need to wait for `ethereum-types` release, and then I can update `web3`.

**Comment by harishbm34** [comment]
Your guess is right, I am using ::from_slice inside  the "sputnikvm-precompiled-interchaintrx" crate.

We need to wait for ethereum-types release, and then I can update web3 --> thanks a lot for your help. I was wondering about the warnings. Now realised, that's not the issue with  "rust-web3". Let's wait for ethereum-types crate release. You can proceed to close this issue.

**Comment by tomusdrw** [comment]
@harishbm34 ok, cool. Will try to release new web3 as soon as ethereum-types is up on crates.io. Cheers!

**Comment by D4nte** [comment]
Hi @tomusdrw, ethereum-types is now released on crates.io. Version 0.5.2 that depends on fixed-hash 0.3.

Can you please update web3?

**Comment by tomusdrw** [comment]
@D4nte see https://github.com/paritytech/ethabi/pull/149
