### ISSUE TITLE
how to run examples with ganache?

### ISSUE THREAD

**Issue by jedahan** [tomusdrw/rust-web3#182]
I am trying to run the contract example against ganache, and no matter how high the gas limit is set, I get an error deploying the contract with "base fee exceeds gas limit".  I would love it if the readme could include documentation on how to test the examples.

**Comment by tomusdrw** [comment]
@jedahan can you provide logs from ganache and `rust-web3`?
You need to intialize `env_logger` in your application and then run with `RUST_LOG=web3=trace`

**Comment by tomusdrw** [comment]
To be frank I don't remember where that code comes from - perhaps the contract is just invalid? Do you mind compiling some of the examples of solidity code in the repo and deploying that?

**Comment by jedahan** [comment]
So the simple_storage example works, but I'm not sure what source .sol corresponds to the code in that folder

**Comment by tomusdrw** [comment]
The code that is being deployed in `contract.json` example is just invalid, it's a JSON file not solidity bytecode.
We should compile a simple token example and deploy this instead.

**Comment by tomusdrw** [comment]
Closed via #351
