### ISSUE TITLE
Linked Libraries in Bytecode

### ISSUE THREAD

**Issue by fredfortier** [tomusdrw/rust-web3#186]
I read every contract deployment example in this library. They all assume that the bytecode is a hex string that can be parsed into a byte array like this: `Contract::deploy(web3.eth(), include_bytes!("./build/SimpleEvent.abi"))`.

I'm pre-compiling my contracts with Truffle 5 and reading the bytecode form the `bytecode` attribute of the `build/contracts/MyContract.json` files. I'm observing two issues:
1. Truffle adds a `0x` prefix. This is easy, we just ignore the first two characters.
2. Truffle adds ascii library placeholders, like this: https://github.com/ethereum/solidity/issues/635. It appears that the solc-js compiler of Truffle uses the old method (fully qualified name of the library). However, based on this document: https://solidity.readthedocs.io/en/v0.5.3/using-the-compiler.html library placeholders are a Solidity compiler feature (not a Truffle quirk) and still use ascii characters: `If your contracts use libraries, you will notice that the bytecode contains substrings of the form __$53aea86b7d70b31448b230b20ae141a537$__. These are placeholders for the actual library addresses. The placeholder is a 34 character prefix of the hex encoding of the keccak256 hash of the fully qualified library name. `

Note that I made sure to properly link my libraries before compiling my contract. How do you suggest handling library placeholders with rust-web3?

About my compiler:
```
truffle(develop)> version
Truffle v5.0.2 (core: 5.0.2)
Solidity v0.5.0 (solc-js)
Node v10.15.0
```

**Comment by tomusdrw** [comment]
I think the best way would be to introduce some pre-processors or contract-wrapper types, I'm happy to have them in the `rust-web3` repo. See also #184.

So the idea I have in mind:
```rust
use web3::contract;

// this reads the ABI and bytecode and creates the `ContractBuilder` instance.
let builder = contract::from_truffle::deploy(include_bytes!("./build/contracts/MyContract.json"), {
  let mut map = HashMap::new();
  map.insert("LibraryName", "0x123...456".parse().unwrap());
  map
});
// now we can deploy it (note the code is not required here)
builder.execute(params, from);

// Similar for interacting with existing contracts (this reads the ABI only)
let contract = contract::from_truffle::new(include_bytes!("./build/contracts/MyContract.json"));
contract.call();
```
and for the case in #184 
```rust 
let contract = contract::from_solc::new(include_bytes!("SolidityOutput.json"));
...
```
and for current case
```rust
let contract = contract::from_abi::new(include_bytes!("Abi.ABI"));
...
```

**Comment by fredfortier** [comment]
What would this method do with the bytecode after the library placeholders in the bytecode? I'm confused by this, according to line 358 here: https://github.com/trufflesuite/truffle-contract/blob/ae32dbb2ace5919f69ae81aaac34a3c9b25f2681/contract.js, these placeholders represent unlinked library which should not be allowed in the bytecode during deployment. Should the business logic simply verify that the library does exist at the specified address and remove the placeholder + following bytecode? This begs the question as to why Truffle inserts these library placeholders in both the `bytecode` and `deployedBytecode` attributes even after linking the libraries. If you don't know the anwser, I'll investigate further.

**Comment by tomusdrw** [comment]
Exactly, it would do all the necessary pre-processing to create an instance of contract. I'm proposing a new API here so some refactoring would be required to actually avoid much repetition, but since we already have 3 different use cases of reading ABI/bytecode data from files it might be worth it.

For anyone interested in implementing this - I'm also ok with a partial solution of just processing those files in rust to spit out ABI as `&[u8]` and bytecode as `&[u8]`. The refactoring / common API can be done separately, but at least we have some common aim.

**Comment by fredfortier** [comment]
Ok thanks! For now, I'll just submit a PR with a static method that implements this particular pre-processor (partial solution suggested). Later, either I or another volunteer can refactor the deploy builder carefully as you suggested.
