### ISSUE TITLE
[Question] how to spawn limited number of batch requests?

### ISSUE THREAD

**Issue by ishanjain28** [tomusdrw/rust-web3#193]
Hi there, 

My code is here,

```rust
extern crate itertools;
extern crate tokio_core;
extern crate web3;

use itertools::Itertools;
use web3::{
    futures::{self, Future, Stream},
    types::{Block, BlockId, BlockNumber, Transaction},
};

// only restricts requests that will be sent paralllely in a batch request.
const MAX_PARALLEL_REQUESTS: usize = 128;

fn main() {
    let mut event_loop = tokio_core::reactor::Core::new().unwrap();

    let transport = web3::transports::Http::with_event_loop(
        "http://localhost:50000",
        &event_loop.handle(),
        MAX_PARALLEL_REQUESTS,
    )
    .unwrap();
    let remote = event_loop.remote();
    let web3 = web3::Web3::new(web3::transports::Batch::new(transport));

    let (low, high) = (0, 7_000_000);

    for j in (low..high).chunks(50).into_iter() {
        for i in j {
            let block = web3
                .eth()
                .block_with_txs(BlockId::Number(BlockNumber::Number(i)))
                .then(move |block| {
                    // do stuff with block
                    Ok(())
                });
            println!("Added {:?}", i);

            remote.spawn(move |_| block)
        }
        
        let result = web3.transport().submit_batch().then(|_| Ok(()));
        remote.spawn(move |_| result);
        event_loop.turn(None);
    }

    loop {
        event_loop.turn(None);
    }
}
```

Currently, This code spawns 7 million tasks in event_loop which takes up quite a bit of memory. 

I want to limit the max tasks that can be spawned in event_loop

I have tried several things including but not limited to, 

1. waiting on `BatchFuture`, pauses event_loop, So not useful.
2. Using a waitgroup which pauses execution upon encountering  a max_limit. Not useful as `event_loop.turn(None)` has to be called on ever iteration other wise program hangs indefinitely. 
3. Future streams, turned out it didn't do anything different than what my current code does. 

... and a couple more stuff. 

I have already checked the example batch.rs and it was not particularly useful for me. 

I have already asked for help in rust on moznet, discord and gitter and I just haven't found a solution to my question. Before I give up and do something else, I wanted to give it one last shot and which is why I asked for help here.

So, Is this even possible and If so, how do I do it? Thanks. :)

**Comment by ishanjain28** [comment]
Nevermind. I only had to use an atomic usize counter and thread::sleep. Sorry for bothering you.

**Comment by tomusdrw** [comment]
You can also have a look at the utilities that `futures` crate provide. For instance you can create a batch of futures, create a stream out of them (`futures_unordered`) and then use `for_each` to convert a `Stream` to a `Future` and spawn that to the event loop. I'd also suggest spawning a second thread to maintain the dispatched tasks and leave one thread only for the event loop.
