### ISSUE TITLE
Fix to edition 2018

### ISSUE THREAD

**Issue by botika** [tomusdrw/rust-web3#205]
The only dependence that gives error chain problems, waiting for https://github.com/rust-lang-nursery/error-chain/pull/255 .

**Comment by tomusdrw** [comment]
We can get rid of `error-chain`, it's deprecated anyway, isn't it?

**Comment by botika** [comment]
Totally agree. We get to this before migrating to Tokyo #146

**Comment by vityafx** [comment]
Guys, who say that the `error-chain` crate is deprecated and why?

**Comment by tomusdrw** [comment]
@vityafx it's definitely not maintained currently (see https://github.com/rust-lang-nursery/error-chain/pull/255#issuecomment-486126145) and uses stuff that is deprecated in the stdlib.
