### ISSUE TITLE
support trace API?

### ISSUE THREAD

**Issue by gzuhlwang** [tomusdrw/rust-web3#207]

**Comment by tomusdrw** [comment]
PRs welcome!

**Comment by gzuhlwang** [comment]
hello, is there any available 3rd library supporting trace function? I am a new baby to rust.

**Comment by tomusdrw** [comment]
@gzuhlwang not that I know, sorry. It should be fairly easy to add them to this library though. I'm happy to accept a PR even with partial implementation of those methods and can also help along way.

**Comment by azastrael** [comment]
Hey :wave:!

Isn't it already supported? (https://docs.rs/web3/*/web3/api/struct.Traces.html)

**Comment by tomusdrw** [comment]
@azastrael Most likely. Closing as it seems implemented, if anything is missing please open new, more specific issue.
