### ISSUE TITLE
Listen smart contract events using Infura nodes?

### ISSUE THREAD

**Issue by BaldyAsh** [tomusdrw/rust-web3#214]
Hi! How can I listen smart contract events using Infura nodes?

**Comment by tomusdrw** [comment]
If Infura supports the regular APIs you simply instantiate the transport and connect to their address.

**Comment by isim95** [comment]
> If Infura supports the regular APIs you simply instantiate the transport and connect to their address.

how can we connect to an address, such as 1inch exchange? Sorry, I'm new to Rust and haven't been able to get the contract_log_pubsub to work
