### ISSUE TITLE
WebSocket transport doesn't seem to work

### ISSUE THREAD

**Issue by PascalPrecht** [tomusdrw/rust-web3#215]
Or, chances are high I'm doing something wrong...

I'm trying to connect to a local parity node which is running in dev mode:

```
parity --config dev
```

I can see that it listens on ports for RPC and WS respectively:

```
❯ lsof -i -P | grep :8545
parity    52573 pascalprecht   57u  IPv4 0xb43966809912373      0t0  TCP localhost:8545 (LISTEN)

❯ lsof -i -P | grep :8546
parity    52573 pascalprecht   55u  IPv4 0xb4396680e39fcd3      0t0  TCP localhost:8546 (LISTEN)
```

Using the RPC code sample from the examples works fine:

```
let (_eloop, transport) = web3::transports::Http::new("http://localhost:8545").unwrap();
let web3 = web3::Web3::new(transport);
let accounts = web3.eth().accounts().wait().unwrap();
println!("Accounts: {:?}", accounts);
```

However, trying to do the same using WebSocket transport with the following code (also from `examples` folder), just seems to wait forever with no emission/output:

```
let (_eloop, transport) = web3::transports::WebSocket::new("ws://localhost:8546").unwrap();
let web3 = web3::Web3::new(transport);
let accounts = web3.eth().accounts().wait().unwrap();
println!("Accounts: {:?}", accounts);
```

As a matter of fact, running `simple_ws.rs` causes the same behaviour and doesn't seem to work. I also noticed that the example source uses port `8545` even for the WebSocket version. Changing it to `8546` doesn't fix it though.

Any ideas on what seems to be wrong here? Also, is there a general channel for quick feedback that I can use for questions (instead of SO, GitHub Issues etc)

Thanks everyone for making rust-web3 a thing!

**Comment by PascalPrecht** [comment]
I'm not super familiar with the Ethereum Spec and its protocols, but something tells me that there are some RPC endpoints that don't really make sense to work with WebSockets?

For example, something like the above, getting the current accounts, isn't a "long-living" operation, so using WebSockets for such an API doesn't make a lot of sense. While an API for getting the minded blocks, as they're coming in is certainly a good case of a WebSocket connection.

Am I totally off here? Are certain endpoints maybe not meant to be used using WS?

**Comment by PascalPrecht** [comment]
After further investigation and reading the parity docs closely, it seems I got `Transport` errors because the request origin wasn't allowed:

```
    --ws-origins=[URL]
        Specify Origin header values allowed to connect. Special
        options: "all", "none". (default: parity://*,chrome
        -extension://*,moz-extension://*)
```

Starting parity with `--ws-origins all` does the trick!

Maybe the error message for https://tomusdrw.github.io/rust-web3/web3/error/enum.Error.html#variant.Transport can be improved?

Closing this one as fixed.

**Comment by tomusdrw** [comment]
Hi @PascalPrecht, glad you figured it out I was just about to investigate this.

We can't really improve the transport message cause the rejection from the server is opaque to us. The  origin issue though should be visible in Parity's logs.

Regarding RPC methods over WebSockets - all methods supported on HTTP are also supported on WS, The JSON-RPC protocol is transport agnostic, it only needs to be able to send messages and receive responses. For WS it happens over single connection completetly asynchronously, for HTTP every request-response pair is just HTTP req-res.

Transports with persistent connections can support additional methods like Publish-Subscribe that you've mentioned.

**Comment by PascalPrecht** [comment]
@tomusdrw thank you so much for clarifying this!

> For WS it happens over single connection completetly asynchronously

This was something I wasn't sure about it. AFAIK Rust is pretty much synchronous and the API

```
let accounts = web3.eth().accounts().wait().unwrap();
```

looks very synchronous as well (JavaScript developer speaking here, haha).

So one thing that's still unclear to me: does web3 take care of closing the socket connection after a one-off call? Is it related to dropping the event handle?

Thanks again for your insights!

**Comment by tomusdrw** [comment]
> looks very synchronous as well (JavaScript developer speaking here, haha).

The `.wait()` part makes it synchronous, when we get support for `async-await` in Rust it's going to be much nicer, now handling the async code is pretty tricky.

> does web3 take care of closing the socket connection after a one-off call? Is it related to dropping the event handle?

The connection is closed only when you close the server or drop the event loop.

**Comment by PascalPrecht** [comment]
Got it, thanks for clarifying this @tomusdrw !
