### ISSUE TITLE
What's the recommended way to get web3::Error descriptions?

### ISSUE THREAD

**Issue by PascalPrecht** [tomusdrw/rust-web3#216]
Between web3 0.6.0 and latest master there seems to be a breaking change in how web3::Error is implemented. In 0.6.0 I was able to rely on web3::Error to implement `Error` and therefore had a `description()` API. 

This is no longer the case, so i was wondering how I can access a web3::Error's message when wrapping them in my own errors.

**Comment by tomusdrw** [comment]
@PascalPrecht `std::error::Error::description` is soft-deprecated, you should use `Display` instead. That said the fact that our types don't implement this trait is a bug, it got lost during the refactoring.

See #217

**Comment by PascalPrecht** [comment]
@tomusdrw thanks for the very quick update! Looks like I'll have to refactor my codebase to prefer Display over Error::description then first! :)
