### ISSUE TITLE
What's the best way to make `execute()`s `params` dynamic?

### ISSUE THREAD

**Issue by PascalPrecht** [tomusdrw/rust-web3#219]
This is probably more of a Rust language question than related to this library, but I'm having a hard time finding a solution to this...

For example calling

```
.execute(bytecode, U256::from(100), accounts[0]).unwrap()
```

Works fine when the Smart Contract in the bytecode only expects one constructor argument. If it, let's say, expects 2 arguments, this call needs to be changed to sth. like this (the single value turns into a tuple of size 2):

```
.execute(bytecode, (U256::from(100), U256::from(200)), accounts[0]).unwrap()
```

This can be done with #n amount of arguments as long as it's no more than 16 (as far as I understand).

However, what if I don't know the number of arguments at compile time? I'd like to call `execute()` for several bytecodes and the constructor args I only now at runtime.

Is there a way to do this?

**Comment by tomusdrw** [comment]
@PascalPrecht If you looke at the docs of `execute` function:
https://docs.rs/web3/0.6.0/web3/contract/deploy/struct.Builder.html#method.execute

It takes `params: P` where `P: Tokenize`. So it's totally fine to write your code in a way that moves `Tokenize` around or just plain `Vec<Tokens>` that `Tokenize` is returning.

I hope `Tokenize` is implemented for `Vec<Tokens>` as it should be, if not then it's a bug.

**Comment by PascalPrecht** [comment]
Hi @tomusdrw thanks for getting back to me here.
So I did look at the docs, in fact, I've studied the source haha. 

> I hope Tokenize is implemented for Vec<Tokens> as it should be, if not then it's a bug.

I guess this depends on what "should be" means here. If you pass a `Vec<Tokens>` to `execute()`, it seems like it's being interpreted as 1 parameter that is an array of token. If you want to apply multiple parameters, Tuples seem to be the way to go.

Right now what I'm doing is actually creating a `Vec<Token>` out of some data that I'm getting, and then based on the `count()` I'm decided whether I want to call `execute()` with a tuple of size #n

E.g.

```
match params.count() {
  0 => execute(..., (), ...)
  1 => execute(..., params[0], ...)
  2 => execute(... (params[0], params[1]), ...)
  ...
  10 => ...
  - => // error, too many args (rust-web3 handles up to 16 parameters, I went for 10 for no particular reason)
}
```

Does that make sense?

**Comment by tomusdrw** [comment]
>  If you pass a Vec<Tokens> to execute(), it seems like it's being interpreted as 1 parameter that is an array of token.

I just looked at the implementation and indeed that what happens, due to following implementations:
```
impl <T: Tokenizable> Tokenize for T {
  fn into_tokens(self) -> Vec<Token> {
        vec![self.into_token()]
  }
}

impl <T: Tokenizable> Tokenizable for Vec<T> {}
impl Tokenizable for Token {}
```

So indeed a `Vec<Token>` is converted to a single `Token` that represents an array.

To overcome you can convert `Vec<Token>` to `&[Token]`, so just pass `&*arg` instead of `arg`, but it feels a bit hacky.

I don't have a good idea how to handle `Vec<Token>` correctly without specialization, maybe we should remove `Tokenizable for Token` implementation and implement `Tokenizable for Vec<Token>` instead.

**Comment by PascalPrecht** [comment]
Thanks again for coming back to me here.

I'm certainly no expert in this here, but I'm also not sure if the behaviour for `Vec<Token>` should change either. After all, you may actually want to pass an array as a parameter, unless I'm totally off here.

I'm personally fine with pattern matching the vec count for now and applying tuples of size #n. 

Just wasn't sure if that's the way to go in Rust (still learning the language), or if there's other patterns for scenarios like this.

If you think this is okay, we can also close this issue.

Appreciate your thoughts on this! 🙏

**Comment by tomusdrw** [comment]
@PascalPrecht You're welcome!

Actually you don't have to do pattern matching, try this instead:
```
let params: Vec<Token> = ...;
execute(..., &*params, ...);
```

and it should work correctly, because of the inconsistencies in handling `Vec<Token>` and `&[Token]`

**Comment by PascalPrecht** [comment]
This works as intended, thanks @tomusdrw !

I'm not sure I fully understand what this syntax is doing yet. I understand it's a reference to `params` which then dereferences at the same time. However, I'm not sure I follow how that is actually solving the problem :D

If you feel like shedding some light on this, that'd be wonderful! Otherwise, I'm gonna go ahead and close this as solved.

Landed as https://github.com/PascalPrecht/vibranium/commit/3052ff343acffc502d038a84399b86c669208c53

Thanks again!

**Comment by tomusdrw** [comment]
So the difference is in `Tokenize` implementation, roughly:
```rust
/// This converts a slice to multiple parameters
impl Tokenize for &[Token] {
  fn into_tokens(&self) -> Vec<Token> {
     self.to_vec()
  }
}

/// This converts a vector to a single parameter (that is an array)
/// You won't find such implementation in the code, cause it goes through more indirection.
impl Tokenize for Vec<Token> {
  fn into_tokens(&self) -> Vec<Token> {
     vec![Token::Array(self)]
  }
}
```
And now if you look at the details of `Vec<T>` in Rust documentation, you will see it implements `Deref`:
```
impl <T> Deref for Vec<T> {
  type Target = [T];
  fn deref(&self) -> &[T] { self.as_slice() }
}
```
So you can convert `Vec<T>` into `[T]` with dereferencing syntax, i.e. `*`.

Syntax `&*` is `Deref` + take a reference, so we deref `Vec<Token>` into `[Token]` and then take a reference so we get `&[Token]`.
This results in different (correct) `Tokenize` being used.

**Comment by PascalPrecht** [comment]
Wow thank you @tomusdrw for taking the time! This makes much more sense now.
