### ISSUE TITLE
Any plans to release a new version?

### ISSUE THREAD

**Issue by PascalPrecht** [tomusdrw/rust-web3#220]
I'm close to publishing a first version of https://github.com/pascalprecht/vibranium, however, since it's depending on a rust-web3 version that points to a commit on GitHub, I need to download it into my own repo to publish it along side my project.

It'd be great if that can be avoided with a new release of rust-web3. Is there anything planned?

**Comment by tomusdrw** [comment]
Just published 0.7: https://github.com/tomusdrw/rust-web3/releases/tag/v0.7.0

Thanks for heads up!

**Comment by PascalPrecht** [comment]
Thanks man!
