### ISSUE TITLE
eth.transaction getting Io(Kind(BrokenPipe))

### ISSUE THREAD

**Issue by rodoufu** [tomusdrw/rust-web3#226]
I'm trying to get a transation by the transaction hash but I'm getting the Error `Io(Kind(BrokenPipe))`, what am I missing?

I'm using a unit test to run it, but I keep getting this error, I've tried using Node.js and it works.
Everything is working on a single thread.

```
let web3 = Web3::new(&self.transport);
let transaction = web3.eth().transaction(TransactionId::Hash(transaction_hash))
    .wait()
    .map(|x| x.expect("get_transaction_sync - transaction not found"))
    .map_err(|e| format!("get_transaction_sync: ERROR {:?}", e));
```

**Comment by tomusdrw** [comment]
What backend are you connecting to? Do you mind adding `env_logger` to your app and running with `RUST_LOG=web3=trace`?

**Comment by rodoufu** [comment]
I'm connecting to Ganache, I 'm going to post more info today later.

**Comment by tomusdrw** [comment]
Most likely same issue as #227
