### ISSUE TITLE
Use `status` field to determine if deployment was successfull

### ISSUE THREAD

**Issue by geigerzaehler** [tomusdrw/rust-web3#241]
At the moment, contract deployment is considered successful if the `contractAddress` field in the receipt for the deployment transaction is set ([code](https://github.com/tomusdrw/rust-web3/blob/7c80ad3368d9a6d32ea92a91bca963268a16b9c2/src/contract/deploy.rs#L124-L125)). This behavior does not yield correct results with `parity-ethereum`. `parity-ethereum` provides the `contractAddress` even if the contract failed to deploy at least in some circumstances (https://github.com/paritytech/parity-ethereum/issues/10925). However it sets the `status` field in the receipt correctly.

I don’t know if behavior is the same beyond the narrow scenario I tested it with nor do I know if this behavior is intended or consistent with other ethereum implementations.

I would suggest that in addition to checking the `contractAddress` we should also check the status to determine if the deployment was successful. (I’d be willing to make a PR myself)

**Comment by tomusdrw** [comment]
That sounds good to me. I'd fallback to `contractAddress` detection if `status` is `null` though (for backward compatibility).
