### ISSUE TITLE
No webassembly support 

### ISSUE THREAD

**Issue by AchalaSB** [tomusdrw/rust-web3#245]
Hi,
I'm compiling rust code to webassembly. My code contains `web3 crate`. While doing `cargo run` getting errors(socket errors `as_sock()` ). seems like web3 is not supporting webassembly.

When will expect web3 to support webassembly??
Or is there is any alternatives?

Thanks in advance

**Comment by tomusdrw** [comment]
Compiling web3 to wasm is currently not supported, see: https://github.com/tomusdrw/rust-web3/issues/21

We've not put any effort yet into porting it, but it might be as simple as adding a conditional `no_std` feature and disabling all the transports (+ most likely using non-std versions of deps). Note however that producing a separate transport that uses JS `fetch` would most likely be required to actually connect to the node.

**Comment by AchalaSB** [comment]
@tomusdrw Thanks for update. 

Is there any other rust crate using which I can connect to ethereum ? of course with webassembly support??
Have checked `jsonrpc` crate https://github.com/paritytech/jsonrpc where you are contributing as well. But there I didn't see any function call to connect ethereum.

**Comment by tomusdrw** [comment]
@AchalaSB no other crate, as far as I know, sorry.

**Comment by AchalaSB** [comment]
@tomusdrw  Just need some clarification 
when I tried to compile this code to wasm got error for socket
```
error[E0599]: no method named `as_sock` found for type `&udp::UdpBuilder` in the current scope
    --> /home/achala/.cargo/registry/src/github.com-1ecc6299db9ec823/net2-0.2.33/src/ext.rs:1499:22
     |
1499 |         get_opt(self.as_sock(), SOL_SOCKET, SO_ERROR).map(int2err)
     |                      ^^^^^^^
     |
     = help: items from traits can only be used if the trait is implemented and in scope
     = note: the following trait defines an item `as_sock`, perhaps you need to implement it:
             candidate #1: `ext::AsSock`
```
Is this because of websocket library you are using? If so that library is required to connect to ethereum?
I'm trying to alter this library only. if any of the dependencies is not really required will skip those or else have to make all dependency as compatible its too hard for me.

Please give a direction
Thanks

**Comment by tomusdrw** [comment]
You should definitely avoid compiling anything that touches IO (disk, networking, etc), cause it will for sure fail.
That might require feature-gating some stuff. Make sure that you are not compiling any transports.

**Comment by AchalaSB** [comment]
Thanks @tomusdrw 
Have modifying this library. Remove all the unwanted stuff for my application
Replaced `hyper` with `http` to call the requests. 
but getting an error
```
error[E0433]: failed to resolve: could not find `Http` in `transports`
 --> examples/simple.rs:6:52
  |
6 |     let (_eloop, http) = web3::transports::Http::new("http://localhost:8545").unwrap();
  |                                                    ^^^^ could not find `Http` in `transports`

error: aborting due to previous error
``` 
can help me to resolve this error

**Comment by tomusdrw** [comment]
@AchalaSB web assembly will not really support any transports at all. The way you can actually contact the server will depend heavily on you target (browser, wasi) and the transport need to be specific to this.
