### ISSUE TITLE
How can I serialise BlockHeader to RLP?

### ISSUE THREAD

**Issue by k06a** [tomusdrw/rust-web3#255]
I wish to serialize BlockHeader back to RLP as it was store in Ethereum blockchain. I wonder if it is possible with `Serialize`?

**Comment by tomusdrw** [comment]
No it's not. The types in this crate are not RLP-serializable. There is a separate crate to do so here: https://docs.rs/crate/rlp/0.4.2

And the format is here: https://github.com/paritytech/parity-ethereum/blob/00124b5a4bf8a38ad6c660b462a5e5addf13cab3/ethcore/types/src/header.rs#L293

**Comment by k06a** [comment]
Maybe to import basic types from https://docs.rs/ethereum-types/0.1.1/ethereum_types/ intead on reimplementing it to support this `rlp` library natively?

**Comment by tomusdrw** [comment]
@k06a That's what we do for the primitive types indeed: https://github.com/tomusdrw/rust-web3/blob/master/src/types/uint.rs#L1

`ethereum-types` does not contain the higer-level types like `BlockHeader` though.

**Comment by k06a** [comment]
@tomusdrw, cool! What about `ethereum-block` lib?

**Comment by tomusdrw** [comment]
Fine with me. I'd also accept a PR with an optional compilation feature to `rust-web3` to support RLP encoding.
