### ISSUE TITLE
What is the need for the `EventLoopHandle`?

### ISSUE THREAD

**Issue by thomaseizinger** [tomusdrw/rust-web3#264]
We have using this library for a while and I've always wondered, why creating an HTTP transport returns you an `EventLoopHandle` that you have to keep around.

All the methods return Futures. Why can't these Futures not just encode all the work that needs to be done in order to return the response?

I've looked into the code a bit and couldn't find any apparent reason of why a background thread is used to process all the requests.
Can someone shed some light onto this? Thanks :)

**Comment by tomusdrw** [comment]
Hey @thomaseizinger!

It's mostly historical reasons, the large part of the code is still based on `tokio-core` and I've tried to hide it as implementation detail.
Now that futures are stabilised, I'm happy to move on and rewrite everything to be future-based. Might actually be worth to wait a bit longer and rewrite to async-await.

**Comment by thomaseizinger** [comment]
> Now that futures are stabilised, I'm happy to move on and rewrite everything to be future-based. Might actually be worth to wait a bit longer and rewrite to async-await.

Interesting, thanks for the insight! :)

**Comment by WyseNynja** [comment]
[Async/await is stable!](https://blog.rust-lang.org/2019/11/07/Async-await-stable.html)

Would it be better to change web3 to use tokio instead of tokio_core, or should it be changed to use futures and then each application can choose their own executor?

I think we might need to keep tokio because they provide timers.

**Comment by thomaseizinger** [comment]
It would be nice to not force an executor onto consumers of the library if it is not strictly necessary :)

**Comment by rodoufu** [comment]
> [Async/await is stable!](https://blog.rust-lang.org/2019/11/07/Async-await-stable.html)
> 
> Would it be better to change web3 to use tokio instead of tokio_core, or should it be changed to use async/await and then each application can choose their own executor?
> 
> I think we might need to keep tokio because they provide timers.

I agree, tokio_core's been deprecated a long time ago.

**Comment by tomusdrw** [comment]
Closed via #351
