### ISSUE TITLE
How to create an account and retrieve a private key ?

### ISSUE THREAD

**Issue by stanislasdrg** [tomusdrw/rust-web3#266]
Hello,
I am trying to create an account by using something similar to the web3.js function  [web3.eth.accounts.create([entropy])](https://web3js.readthedocs.io/en/v1.2.1/web3-eth-accounts.html#).
I have gone through both the code and the docs and - correct me if I am wrong - it looks like these APIs have not been implemented. Is there any workaround that I have missed ?

Edit : I have discovered that the whole library is based on the Parity Wallet, however I cannot find a way to retrieve the private key in one call as mentioned above. Do you have to manually get the key from your disk ?

**Comment by tomusdrw** [comment]
The nodes handling private keys is not secure and is not going to be supported going forward. I think since then we now have signing API support at web3. If not, take a look at https://github.com/tomusdrw/ethsign
