### ISSUE TITLE
Support EIP-1898 - geth state-related RPC methods now support specifying block hashes as well as block numbers

### ISSUE THREAD

**Issue by WyseNynja** [tomusdrw/rust-web3#285]
I noticed that Geth 1.9.6 added support for specifying block hashes for some methods (https://github.com/ethereum/go-ethereum/pull/19491).

https://eips.ethereum.org/EIPS/eip-1898

In my code, I've been passing the block number through, but passing the block hash through will give consistent answers if a re-org happens in the middle of some calls.

I think functions that have `block: Option<BlockNumber>` in their args would need to change, but I haven't thought about exactly how yet.

https://github.com/tomusdrw/rust-web3/blob/f043b222744580bf4be043da757ab0b300c3b2da/src/api/eth.rs#L42

**Comment by tomusdrw** [comment]
I guess we could introduce a `BlockId` enum with `Hash` and `Number` variants.

**Comment by WyseNynja** [comment]
I think that would work. Maybe something like:

```
enum BlockId {
  Number(BlockNumber),
  /// Block hash and a boolean for requireCanonical
  Hash(H256, bool),
}
```

But maybe the BlockNumber enum should have `Hash(H256, bool)` added to it instead? It looks like that would cover all the functions needed. I'm not sure if it covers too much though. The name "BlockNumber" also wouldn't fit as well. I think renaming it to "BlockId" matches the better since it has strings like "latest" and "earliest" in it, too.
