### ISSUE TITLE
Create account from private key

### ISSUE THREAD

**Issue by macrauder** [tomusdrw/rust-web3#286]
Hi,

is there a method to create an account based on an existing private key, similiar to
[https://web3js.readthedocs.io/en/v1.2.0/web3-eth-accounts.html#privatekeytoaccount](https://web3js.readthedocs.io/en/v1.2.0/web3-eth-accounts.html#privatekeytoaccount) so that is possible to us HDWallet keys or simple local keys as an starting point?

thx

**Comment by tomusdrw** [comment]
There is a parity-specific method if you want to create a private key on the node:
https://docs.rs/web3/0.8.0/web3/api/struct.ParityAccounts.html#method.new_account_from_secret

Local signing got just merged recently (#279) and you can use `SecretKey` from `ethsign` crate, which should support arbitrary key (although it doesn't support derivation).
