### ISSUE TITLE
ABIencoderV2/tuple support

### ISSUE THREAD

**Issue by brockelmore** [tomusdrw/rust-web3#288]
I believe the error I am running into is around abi encoder V2 and contracts that use it. 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(SerdeJson(Error("Error(InvalidName(\"tuple\"), State { next_error: None, backtrace: InternalBacktrace })", line: 1, column: 267)), State { next_error: None, backtrace: InternalBacktrace })', src/libcore/result.rs:999:5
```

Happy to try to help, but I am brand new to the library.

**Comment by brockelmore** [comment]
I see that it is upstream in ethabi.

**Comment by samparsky** [comment]
@brockelmore Have you been able to solve this?

**Comment by brockelmore** [comment]
Nope - its upstream here: https://github.com/paritytech/ethabi/issues/113 so it probably wont be fixed any time soon

**Comment by samparsky** [comment]
Were you able to work around it?

**Comment by brockelmore** [comment]
Nope pretty fundamental to interacting with latest smart contracts like dydx and many other defi protocols. I use rust and compile down to wasm so I am able to pass JavaScript values in and sidestep doing it in rust all together

**Comment by fordN** [comment]
@samparsky @brockelmore I've added support for Solidity Structs/Tuples in a [forked ethabi](https://github.com/graphprotocol/ethabi/tree/graph-patches) repo that we use in [graph-node](https://github.com/graphprotocol/graph-node) Maybe you'll find it useful here. :)

I would like to write up a PR and work on getting my changes merged into the original ethabi repo here, but unfortunately it is not a priority at the moment so I can't give a timeline on when that will be completed.

**Comment by chabashilah** [comment]
@fordN The PR will be super helpful!! Thank you!!

**Comment by brockelmore** [comment]
> @samparsky @brockelmore I've added support for Solidity Structs/Tuples in a [forked ethabi](https://github.com/graphprotocol/ethabi/tree/graph-patches) repo that we use in [graph-node](https://github.com/graphprotocol/graph-node) Maybe you'll find it useful here. :)
> 
> I would like to write up a PR and work on getting my changes merged into the original ethabi repo here, but unfortunately it is not a priority at the moment so I can't give a timeline on when that will be completed.

Btw, I think there is a bug in your tuple parsing around dynamic length bytes. Check out this fork for a working [version](https://github.com/cryptoeconomicslab/ethabi).

A good test is to use it with dYdX txs, which your version fails for

**Comment by fordN** [comment]
@brockelmore, thanks for testing!  Kind of incredible that I haven't come across that issue already given that it's been used successfully with many contracts. 

I'd love to replicate the failure scenario you found and dig into it. Steps to repeat?

**Comment by fordN** [comment]
@chabashilah great to know! In that case, I'll try to get that PR review process kicked off this week.

**Comment by dvdplm** [comment]
> I would like to write up a PR and work on getting my changes merged into the original ethabi repo here, but unfortunately it is not a priority at the moment so I can't give a timeline on when that will be completed.

@fordN if/when you do get a chance to upstream your changes, ping me and I'll try to get it reviewed asap.

**Comment by fordN** [comment]
Hey @dvdplm, just a heads up that I've submitted [PR#174](https://github.com/paritytech/ethabi/pull/174) with the Tuple support updates. :)

**Comment by Jannis** [comment]
@brockelmore Tuple support has been merged into https://github.com/paritytech/ethabi. Can you check whether it still has the tuple parsing issue and if so, file an issue in the ethabi repo so we can take a look?

**Comment by chabashilah** [comment]
If I change the version of ethabi to latest one in rust-web3, is ABIencoderV2/tuple able to use?
