### ISSUE TITLE
Contract method call data to Bytes for web3::types::TransactionParameters

### ISSUE THREAD

**Issue by khangle27** [tomusdrw/rust-web3#298]
@tomusdrw 

I'm trying to use the `sign_transaction()` method which takes `TransactionParameters` as one of its parameters. I'd like to encode to Bytes the ERC20 smart contract standard's `transfer(address _to, uint256 _value)` method call but cannot find a way to do so with rust-web3. 
In web3js, [`methods.myMethod.encodeABI` ](https://web3js.readthedocs.io/en/v1.2.0/web3-eth-contract.html#contract-encodeabi) does that. 

I was wondering whether I am missing something?

**Comment by tomusdrw** [comment]
Take a look at `ethabi` library: https://github.com/paritytech/ethabi it can be used to encode calls, the tight integration is between these two is still open #120
