### ISSUE TITLE
Use reqwest as client library for WASM browser support

### ISSUE THREAD

**Issue by olanod** [tomusdrw/rust-web3#303]
Having a quick glance to the dependencies I see you depend on hyper directly, would it be a big effort to use reqwest instead? is one of the most used http clients this days and provides a nicer API, on top of that they already went through the effort of making it work with web assembly which seems like a major effort that this project doesn't look very motivated to take. Reqwest would act as the abstraction layer that makes the switch from a hyper backend to browser fetch at compile time.  
Nicer http api plus wasm support, sounds like a nice deal right?

**Comment by tomusdrw** [comment]
PRs welcome! :)

**Comment by tomusdrw** [comment]
Another reason to use `reqwest` or some alternative http client library would be to get rid of `tokio` runtime dependency. See #362

**Comment by lclc** [comment]
Using reqwest would also allow to get rid of OpenSSL as dependency and use rustls-tls instead.

**Comment by sinkingsugar** [comment]
I might give it a go. 

I'm facing a hard choice, my native code uses rust-web3 but I now need to run it on the web via WASM. I'm trying to understand if it's worth to use JS web3 and reimplement the abstraction on top of it in c++/wasm, or contribute here to add WASM support (and use my existing code as is).

Any other blocker towards a WASM build that you guys might think of?

**Comment by tomusdrw** [comment]
@sinkingsugar that's awesome! Happy to help if needed. If I were you, I'd start off with `no_std` compilation without any transports to make sure that all dependencies do support that and only then attempting to implement the transport layer (which should rather be straight forward).

**Comment by sinkingsugar** [comment]
Thanks, I'll definitely open a draft PR if I get going.
True, that's a good idea, also assessing the `no_std` situation should not really consume so much time.

**Comment by enolan** [comment]
I have a `Transport` that uses EIP-1193, so you can interface with MetaMask in the browser. Should have a PR soonish. If you want your app to work without a browser extension, you can use a JS library that implements the EIP-1193 interface and makes calls to Infura or whatever using the normal browser APIs. It'd be a bit roundabout, but is less work than switching HTTP libraries.

**Comment by tomusdrw** [comment]
@enolan wow, that's awesome! Super excited for the PR, thanks! :heart:

**Comment by toxeus** [comment]
@enolan any status on the progress? I'm considering doing the migration to reqwest myself...

**Comment by enolan** [comment]
Merged in #414 :)

**Comment by toxeus** [comment]
Well done @enolan :+1: I guess this can be closed then @tomusdrw :)

**Comment by olanod** [comment]
So the PR introduces WASM support but not via reqwest right? Great to have browser support, was what I was after initially but then as this issue is about reqwest should it be a won't fix or is a higher level http client(there's also [`surf`](https://github.com/http-rs/surf/)) still something people would like to see? based on the comments it would bring other benefits other than WASM support.

**Comment by toxeus** [comment]
Yeah, I just realized that myself. I still see the benefit in migrating to reqwest as it supports multiple TLS crates.
