### ISSUE TITLE
Error when calling contract

### ISSUE THREAD

**Issue by BaldyAsh** [tomusdrw/rust-web3#306]
Hi, @tomusdrw, thank you for the great project, but I have a problem.
I'm trying to call contract variable as follows:
```rust
let contract = Contract::from_json(web3.eth(), contract_addr, include_bytes!("./build/MyContract.abi")).unwrap();
let result = contract.query("bal", (), None, Options::default(), None);
let balance: u32 = result.wait().unwrap().as_u32();
```

After that I the error occurs:
```
error[E0282]: type annotations needed for `web3::contract::result::QueryResult<R, <T as web3::Transport>::Out>`
  --> src/contract.rs:42:9
   |
41 |     let result = contract.query("bal", (), None, Options::default(), None);
   |         ------ consider giving `result` the explicit type `web3::contract::result::QueryResult<R, <T as web3::Transport>::Out>`, with the type parameters specified
42 |     let balance: u32 = result.wait().unwrap().as_u32();
   |         ^^^^^^ cannot infer type
```

As I understand I need to specify Detokenize type, but it bothers me that in the examples it works the way I wrote ([for example here](https://github.com/tomusdrw/rust-web3/blob/master/examples/simple_storage.rs#L36)) How can I correctly set this type?

**Comment by tomusdrw** [comment]
@BaldyAsh you seem to be calling `.as_u32()` so ti means you expect a particular type to be returned by `result.wait().unwrap()`. Please try this:
```
let result = contract.query("bal", (), None, Options::default(), None);
let expected: U256 = result.wait().unwrap();
let balance = expected.as_u32();
```
Replace `U256` with the type that you actually expect.

You can also do it in one line:
```
let balance = contract.query::<U256, _>("bal", (), None, Options::default(), None).wait().unwrap().as_u32();
```

Please comment here if it doesnt' solve your issue.
