### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by daviddimariaFF** [tomusdrw/rust-web3#310]
Master is ahead (5 months) of the most recent release (0.8.0).  Do you intend to cut a new release, or at least tag a version to some commit hash in master?  On a related note, is master considered stable, or it it 0.8.0 the latest stable?  Thanks!

**Comment by tomusdrw** [comment]
Thanks for heads up, just released v0.9.0

Current master can be generally considered stable, but I plan a big refactoring to migrate to latest futures and possibly async-await so best not to rely on it directly in the near future.

**Comment by fredfortier** [comment]
@tomusdrw Are you still working on a release using the latest futures?

**Comment by tomusdrw** [comment]
@fredfortier hey! started working on latest future migration few days ago, stay tuned.
