### ISSUE TITLE
Transaction Signing

### ISSUE THREAD

**Issue by nlordell** [tomusdrw/rust-web3#317]
@tomusdrw I see that the transaction signing was removed because of licensing issues with `ethsign`. I’m very sorry that I didn’t even think to check the license (as it was my contribution).

Would you be willing to accept a PR that implements this using libsecp256k1 directly? It is under MIT (https://github.com/bitcoin-core/secp256k1/blob/master/COPYING) and the rust bindings CC0 (https://github.com/rust-bitcoin/rust-secp256k1/blob/master/LICENSE).

**Comment by tomusdrw** [comment]
@nlordell Yes, I'm willing to bring back the account support as I've mentioned in the PR.

No need to apologize, I suggested using the libs myself (being an author of both) and completely forgot about mismatching license.

Another avenue might be attempting to relicense `ethsign` to a more permissive license, but I need to check feasibility of that option.

**Comment by nlordell** [comment]
I looked through the dependencies and it looks like it uses `parity-crypto` which also is licensed under GPL3, I imagine that would complicate things a bit.
