### ISSUE TITLE
Sign data with private key

### ISSUE THREAD

**Issue by simplespy** [tomusdrw/rust-web3#320]
Is there any function the same as eth.accounts.sign(data, private_key) in javascript-web3?

ref: [https://web3js.readthedocs.io/en/v1.2.0/web3-eth-accounts.html#sign](https://web3js.readthedocs.io/en/v1.2.0/web3-eth-accounts.html#sign)

**Comment by tomusdrw** [comment]
There used to be, see #279 However for now it was removed due to mismatching license.

You can use https://github.com/tomusdrw/ethsign or https://github.com/golemfactory/golem-unlimited/tree/release/0.2/ethkey to handle private keys (but note the license is GPL for those libraries).

**Comment by tomusdrw** [comment]
please track #317 for details.
