### ISSUE TITLE
The contract call() function does not change the state of the contract

### ISSUE THREAD

**Issue by cezhang52111** [tomusdrw/rust-web3#334]
I have tried the call function with different contracts. Though there is no error or warning during the execution, the contract state has not been changed. 
For example, in the example `simple_storage`:
```
//Change state of the contract
    contract.call("set", (42,), accounts[0], Options::default());
```
After running this line, the state is not changed to 42. And the result with 
```
 let result = contract.query("get", (), None, Options::default(), None);
```
is still 0.

**Comment by tomusdrw** [comment]
Closed via #351
