### ISSUE TITLE
Transaction index Uint different in Transaction and Log

### ISSUE THREAD

**Issue by brockelmore** [tomusdrw/rust-web3#335]
Transaction index for a transaction type is `Option<U128>` but for a log is `Option<U256>`. These should be consistent

**Comment by tomusdrw** [comment]
PR welcome!

**Comment by brockelmore** [comment]
Do you have a preference if its one way or another? I lean toward U256 but dont really care

**Comment by tomusdrw** [comment]
it's `index` so it means it's bound by regular computer memory anyway, I would even go as far as making it `U64` if that type is available. There should be `U64 -> U128 -> U256` conversions in place anyway, right?

**Comment by brockelmore** [comment]
On log, its a straight `Option<U256>` - no Index. I will update Index to be type U64 and push log to be Index if that is what you think is best?

**Comment by tomusdrw** [comment]
Sounds good!

**Comment by tomusdrw** [comment]
Closed via #336
