### ISSUE TITLE
Eth::block() not working for BlockNumber::Pending

### ISSUE THREAD

**Issue by fleupold** [tomusdrw/rust-web3#342]
The following example code:

```rust
use web3::futures::Future;
use web3::types::BlockNumber;
fn main() {
    let (_eloop, transport) =
        web3::transports::Http::new("https://node.mainnet.gnosisdev.com").unwrap();

    let web3 = web3::Web3::new(transport);
    let block = web3
        .eth()
        .block(BlockNumber::Pending.into())
        .wait()
        .unwrap();

    println!("Block: {:?}", block);
}
```

Fails with the following error:

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Decoder("Error(\"invalid type: null, expected a 0x-prefixed hex string with length of 512\", line: 0, column: 0)")', src/main.rs:8:17

The problem seems to be that the RPC response for a pending block (parity client) contains `null` for `logs_bloom` (512 hex characters = 2048 bit) and this field is not optional on the [`Block` struct](https://github.com/tomusdrw/rust-web3/blob/de125d11d9260c743371e98f18fcec69081e81cd/src/types/block.rs#L89).

Is there a reason for this? Do consumers expect `logs_bloom` to be always set? Would it be a valid change to make this field optional or could we alternatively tighten the interface to not allow querying `block()` for `Pending`?

**Comment by tomusdrw** [comment]
The `Block` struct in `rust-web3` was based on the one returned by Parity Ethereum, but it was a long while ago. Seems that this change: https://github.com/openethereum/openethereum/pull/8281 was not reflected in `web3` copy of the `Block` struct.

I think we should just change the `logs_bloom` to be an `Option`, PR welcome :)

**Comment by yq0810** [comment]
I use the same command(block(BlockNumber::Pending.into())) in infura and have the same error

using
https://github.com/tomusdrw/rust-web3/commit/f68b3a1bb63669fc2e3baf189dc91f9b5f0ef110
