### ISSUE TITLE
v0.12.0: rust-web3 futures only works on the Tokio runtime

### ISSUE THREAD

**Issue by e00E** [tomusdrw/rust-web3#362]
Modify `examples/contract.rs`:

```rust
...
async fn main_() -> web3::contract::Result<()> {
...

fn main() {
    futures::executor::block_on(main_()).unwrap();
}
```

Run the example: `cargo run --example contract`

> thread 'main' panicked at 'not currently running on the Tokio runtime.', /home/work/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/handle.rs:106:9

The stacktrace shows that this is likely because of using hyper.

Most importantly this should be documented.
Then I argue that rust-web3 should be runtime agnostic because it is very limiting for a library to only work with a specific runtime. Consumers of the library should not be forced to use the same runtime.

In the hyper docs the `runtime` feature is described which might allow hyper to be used in a runtime agnostic way. Alternatively there might be other http frameworks that do not have this limitation.

**Comment by tomusdrw** [comment]
I 100% agree with the sentiment that the library should be runtime agnostic, as you can check in `Cargo.toml`, we don't depend on `tokio` directly. Unfortunately `hyper `has a hard-dependency on `tokio` runtime and there is no way around it afaict. (The `runtime` feature just disables the convenient way of creating the default runtime).

I've reworked and documented features in #363 replacing `hyper` with some alternative http client is discussed here, see #303 (although `reqwest` does seem to use `hyper` under the hood, we could potentially switch to something different).

**Comment by e00E** [comment]
Thanks for your response and your work on rust-web3. To be clear, I don't have a problem with the library depending on tokio, just that the runtime shouldn't be required to execute the futures. From looking through the (closed) hyper issues mentioning runtime or async-std I do think it's possible to use it without the tokio requirement but whether that is better or using a different http library I don't know.
