### ISSUE TITLE
Can't get transaction information in time

### ISSUE THREAD

**Issue by yulidai** [tomusdrw/rust-web3#364]
After sending a transaction and being mined, it takes a long time (approximately half an hour) to get the Transaction by using `web3.eth().transaction(tx_hash.into())`. However, using `curl` directly can get it immediately, the query nodes are all infura.

Does rust-web3 need to confirm the block height before returning the value? If yes, how to cancel the default behavior?

the version is `v0.12`

**Comment by tomusdrw** [comment]
@yulidai no, the `Eth::transaction` method does not include any confirmations. We just take the `hash` and issue `eth_getTransactionByHash(<hash>)` RPC method.

Perhaps Infura has some cache for particular clients? I.e. checking with `curl` ends up getting a non-cached response, vs `web3` receiving an old, cached one?

One other option I see is that there are some headers that we could include in the request to tell Infura to disable the cache.

Can you run with tracing and post the requests/responses here?

**Comment by yulidai** [comment]
Sorry I used the wrong node address, it should be the problem of node `https://rpc.slock.it/goerli`
