### ISSUE TITLE
FilterStream violates Future contract by potentially polling a completed future

### ISSUE THREAD

**Issue by e00E** [tomusdrw/rust-web3#393]
I noticed this in one of the async rewrites (which also fixes the problem). This issue is for documentation purposes.

The line
https://github.com/tomusdrw/rust-web3/blob/2c33873488cbf9a27bf38d665138b227521bf51a/src/api/eth_filter.rs#L83
applies the `?` operator to the completed result of the inner future. If this result is ok then there is no bug. If the result is Error we forward the error as part of our stream which means that we don't change `self.state` and that the future stays. If the stream is polled again it will poll the inner future again even though it has already completed (with the previous error) which is not allowed.

**Comment by tomusdrw** [comment]
Good catch, I probably broke it when moving to latest futures, previously the stream could error out as well.
