### ISSUE TITLE
Eth::block() not working for BlockNumber::Pending

### ISSUE THREAD

**Issue by yq0810** [tomusdrw/rust-web3#404]
```web3.eth().block(BlockNumber::Pending.into())```
in infura and have the similar error https://github.com/tomusdrw/rust-web3/issues/342
```Err(Decoder("Error(\"invalid type: null, expected a 0x-prefixed hex string with length of 40\", line: 0, column: 0)")) ```
using commit
https://github.com/tomusdrw/rust-web3/commit/f68b3a1bb63669fc2e3baf189dc91f9b5f0ef110

Working after modification
https://github.com/tomusdrw/rust-web3/pull/405

**Comment by tomusdrw** [comment]
Fixed in #405
