### ISSUE TITLE
Inconsistency in README regarding versioning

### ISSUE THREAD

**Issue by elpiel** [tomusdrw/rust-web3#412]
First of all - great project! We use it on production and it's amazing the work that you've done so far!

I saw that the README is quite inconsistent on how to include it as a dependency.

```
[dependencies]
web3 = { git = "https://github.com/tomusdrw/rust-web3" }
```

Later on there is windows specific installation with `0.11.0` version:

```
web3 = { version = "0.11.0", default-features = false, features = ["http"] }
```

I guess that the latest stable tagged version `0.13.0` should be used?
Would be great to have crates.io badge with version on the README as well.

**Comment by tomusdrw** [comment]
Yup, `crates.io` is recommended, I don't have a fixed release schedule though, so it's more on-demand :)

A badge would be nice indeed, PRs welcome! :)
