### ISSUE TITLE
IPC support missing

### ISSUE THREAD

**Issue by lsunsi** [tomusdrw/rust-web3#415]
I know it was removed recently, but since I'm interested on IPC support and I was left wondering why and how could we get it back, I decided to open this issue up so we can discuss.

What do we need to get the IPC support back?
I'm willing to help if I can.

**Comment by tomusdrw** [comment]
Previously the IPC support was built using [`tokio-uds`](https://crates.io/crates/tokio-uds/0.2.7), but afaict it stil hasn't migrated to new futures (and possibly it never will, cause afaict there is `UnixStream` within `tokio` directly now).

So the transport needs a complete rewrite either using [`UnixStream`](https://docs.rs/tokio/0.3.4/tokio/net/struct.UnixStream.html) (*nix only) or something like [`parity-tokio-ipc](https://github.com/NikVolf/parity-tokio-ipc) for Windows & *nix compatibility.

**Comment by lsunsi** [comment]
@tomusdrw I'm currently working on a implementation using the UnixStream from Tokio for the IPC transport based on the current WebSocket and old IPC implementations. You can expect a pull request about this in a couple weeks, or maybe less.

**Comment by lsunsi** [comment]
@tomusdrw Awesome! Now we're probably going to add the batch transport, or at least the duplex one (because we need it in our project). haha.

**Comment by tomusdrw** [comment]
Looking forward to! :)
