### ISSUE TITLE
Build failed on windows

### ISSUE THREAD

**Issue by HackFisher** [tomusdrw/rust-web3#436]
Details info:

https://github.com/darwinia-network/bridger/pull/96/checks?check_run_id=1608195005#step:4:1483

https://github.com/darwinia-network/bridger/pull/96/commits/f60ed281b34c550665998666f55ac235553105c8#diff-13ee4b2252c9e516a0547f2891aa2105c3ca71c6d7a1e682c69be97998dfc87eL5400

**Comment by tomusdrw** [comment]
@HackFisher IPC transport is not supported on windows, please disable it within your build as detailed in the README. Previous release didn't have IPC at all, so it did work with default features, but git version has IPC transport back.
