### ISSUE TITLE
support for `eth_pendingTransactions`

### ISSUE THREAD

**Issue by mohoff** [tomusdrw/rust-web3#440]
Hi, it seems that the call `eth_pendingTransactions` is currently not supported, while getting a pending block is supported via `block(BlockNumber::Pending.into)` as #404 claims. [A stackoverflow answer ](https://ethereum.stackexchange.com/a/6725) suggests that `eth_pendingTransactions` is Geth specific and thus maybe the reason why it isn't supported here?

If mistaken, I can give the implementation a try with some hints.

**Comment by tomusdrw** [comment]
hey! Happy to accept the PR, the library was originally based on Parity's/OpenEthereum's RPCs, but tries not to be biased towards any particular client (if it's within the RPC spec).

**Comment by mohoff** [comment]
Thanks @tomusdrw . I researched a bit more and found that getting pending transactions is not part of the [standard JSON RPC API](https://eth.wiki/json-rpc/API) but can be found under different names in client-specific calls:

- geth: [`txpool_content`](https://geth.ethereum.org/docs/rpc/ns-txpool#txpool_content). Already supported [in `api/tx_pool.rs`](https://github.com/tomusdrw/rust-web3/blob/b9028631a159c5932f09ecebbf36560481a1903b/src/api/txpool.rs#L32).
- parity/openethereum: [`parity_pendingtransactions`](https://openethereum.github.io/JSONRPC-parity-module#parity_pendingtransactions). Currently not supported although several other `parity_*` calls do exist in this crate.

What is confusing for me is that [`web3.js` supports a `eth_pendingTransactions` call](https://github.com/ethereum/web3.js/blob/4469516316d55e35c5ed43dcb883bcf34a6f337c/packages/web3-eth/src/index.js#L557) but implements none of the official client-specific calls listed above. What do I fail to understand here?

Assuming my digging is correct, we can just add support for `parity_pendingTransactions` and call it a day. This would enable users to fetch pending transactions for both clients. Additionally, does a client-agnostic `eth().get_pending_transactions()` make sense for you as part of this crate?

**Comment by tomusdrw** [comment]
> What is confusing for me is that web3.js supports a eth_pendingTransactions call but implements none of the official client-specific calls listed above. What do I fail to understand here?

Might be some historical reasons, or for instance compatibility with Ganache?

> Assuming my digging is correct, we can just add support for parity_pendingTransactions and call it a day. This would enable users to fetch pending transactions for both clients.

Yes, I like the idea.

> Additionally, does a client-agnostic eth().get_pending_transactions() make sense for you as part of this crate?

If you mean to support Ganache for instance - sure, but please make sure that's the case and we need to document it properly. If you mean to have a call that will attempt to unify Geth and OpenEthereum behaviour - then no, I'd like to keep the APIs as close to the spec and low-level RPCs as possible. We could introduce some more high-level "compat" namespace for this if needed.

**Comment by mohoff** [comment]
Implemented by https://github.com/tomusdrw/rust-web3/pull/451
