### ISSUE TITLE
Update tokio to 1.0

### ISSUE THREAD

**Issue by lsunsi** [tomusdrw/rust-web3#445]
It's a major first release which the whole ecosystem is supporting, so we should probably follow suit in order to provide better compatibility for web3 users.

I realise we can't 'just upgrade' due to underlying packages, so I'll make a list of packages that require tokio and can be upgraded and the ones that are blocking our upgrade.

###### Already updated
- hyper (v0.14)
- hyper-tls (v0.5)

###### Not updated
- async-native-tls (https://github.com/async-email/async-native-tls/issues/26)
- hyper-proxy (https://github.com/tafia/hyper-proxy/issues/19)

**Comment by smessmer** [comment]
hyper-proxy 0.9.0 and async-native-tls master now support tokio 1.0

**Comment by soulmachine** [comment]
bump

**Comment by tomusdrw** [comment]
@soulmachine the PR is pending in #454 but we're still waiting for `async-native-tls` to release new version to crates.io.
