### ISSUE TITLE
Is there the implementation of "abi.encodePacked" in solidity?

### ISSUE THREAD

**Issue by algorithmicbtc** [tomusdrw/rust-web3#447]
I can't find any related code in docs.rs.

**Comment by tomusdrw** [comment]
@algorithmicbtc This is is something that `ethabi` should be dealing with (see https://github.com/rust-ethereum/ethabi), but having seen this: https://github.com/rust-ethereum/ethabi/issues/179 I believe it might not be implemented.

**Comment by algorithmicbtc** [comment]
Thank you for your advice!
