### ISSUE TITLE
serde deserialization fails if arbitrary-precision is enabled

### ISSUE THREAD

**Issue by marcbaque** [tomusdrw/rust-web3#460]
If a user is using the `"arbitrary-precision"` feature of `serde`, the deserialization occurring in the following line fails:

https://github.com/tomusdrw/rust-web3/blob/11277e07fd4ebbb4209a96860cb00a0184115016/src/transports/http.rs#L193

Error returned:
`Error("data did not match any variant of untagged enum Response", line: 0, column: 0)`

Workaround:
If the user has arbitrary-precision activated an extra step must be done:
```
fn single_response<T: Deref<Target = [u8]> + std::fmt::Debug>(response: T) -> error::Result<rpc::Value> {
    let value = serde_json::from_slice::<rpc::Value>(&*response).map_err(|e| Error::InvalidResponse(format!("Parse error: {:?}", e)))?;
    let response = serde_json::from_value(value).map_err(|e| Error::InvalidResponse(format!("Parse error: {:?}", e)))?;

    match response {
        rpc::Response::Single(output) => helpers::to_result_from_output(output),
        _ => Err(Error::InvalidResponse("Expected single, got batch.".into())),
    }
}
```

Related issues:
- jsonrpc-client: https://github.com/paritytech/jsonrpc/issues/520
- serde-json: https://github.com/serde-rs/json/issues/505

**Comment by tomusdrw** [comment]
@marcbaque PRs welcome :)
