### ISSUE TITLE
ENS api

### ISSUE THREAD

**Issue by SionoiS** [tomusdrw/rust-web3#463]
Hello!

I'm currently using web3.js but with WASM & ENS support, I would rather use this crate. You guys did a great job!

WASM seams to be working fine even if it's not documented anywhere and for ENS, I found this https://github.com/hhatto/rust-ens but it's 3 years old.

Could someone give me a 10,000ft overview of what would need to be done? Ethereum is new to me...

Thanks!

**Comment by tomusdrw** [comment]
Can you explain a little bit more what you are trying to achieve? Using `ENS` is simply making contract calls and `rust-web3` is providing a low-level API for this. `rust-ens` is a more use-friendly wrapper for that.

**Comment by SionoiS** [comment]
I think mirroring what web3.js has in term of api for ENS is what I'm looking for. Would such an api be at home in this crate or should I build another?

**Comment by SionoiS** [comment]
See #467
