### ISSUE TITLE
Can I use this for getting balance of Ethereum mainnet wallet?

### ISSUE THREAD

**Issue by frankli-dev** [tomusdrw/rust-web3#469]
Could anyone help me if this library can be used to get balance of Ethereum mainnet wallet, please?
If so, please attach some code snippet.
Thanks in advance

**Comment by tomusdrw** [comment]
Yes, please take a look at [examples](https://github.com/tomusdrw/rust-web3/blob/master/examples/transport_http.rs#L12).
