### ISSUE TITLE
How can I convert U256 division to float type?

### ISSUE THREAD

**Issue by frankli-dev** [tomusdrw/rust-web3#471]
I would like to divide balance by decimals.. but it should be float. i use U256 for balance type.. how can I convert balance division to float type?
Thanks in advance

**Comment by tomusdrw** [comment]
```
let x = U256::from(5_412);
let decimal_part = x / 1_000.into();
let fractional_part = x - decimals * 1_000.into();
```
This is outside of the scope of that repo though.

**Comment by Raduc4** [comment]
@tomusdrw  How can I convert a U256 to a float or at least u128 type ?
