### ISSUE TITLE
How to pass arguments as array in contract call?

### ISSUE THREAD

**Issue by zandent** [tomusdrw/rust-web3#475]
Hi there,
I am trying to fit an array as argument for contract::call(). In solidity the input argument is "uint8[4] memory hoster_IP_addr".
I use "[1_u8,1_u8,1_u8,1_u8]" as the params for contract::call(). Then it threw "Error: Api(Decoder("InvalidData"))".
How do I pass in correct format?

**Comment by tomusdrw** [comment]
Please provide a full example, I don't see a reason why it wouldn't work.

**Comment by tomusdrw** [comment]
:thinking: If you are getting a `Decoder` error it's rather the OUTPUT type that is incorrect.

**Comment by zandent** [comment]
Sure. So in solidity:
'''
    function TransferFunc(
        address payable[] memory senders, 
        address payable[] memory receivers, 
        ...
    ){....}
'''
Here I want to call the function in RUST using "call_with_confirmations()":
'''
    let tx = contract.call_with_confirmations(
        "TransferFunc", 
        (
            i_senders,
            i_receivers,
        ),
        account, 
        Options::with(
            |opt| opt.gas = Some(3_000_000.into())
        ), 
        1)
        .await?;
'''
What shoud I construct my "i_senders" and "i_receivers"?
Thanks!

**Comment by zandent** [comment]
Also, how do I receive error message from Ethereum node when using call_with_confirmations()? 
In a function in solidity, I use some require("...") statements to raise error. I saw the error message in the Ethereum node under verbose mode but I didn't receive RPC error reports when using call_with_confirmations(). May I ask how to receive the error message?

**Comment by tomusdrw** [comment]
> What shoud I construct my "i_senders" and "i_receivers"?

That's quite different than the example in the original post. Here I think you simply need:
```
let i_senders: Vec<Address> = vec![];
let I_receivers: Vec<Address> = vec![];
```


>  I saw the error message in the Ethereum node under verbose mode but I didn't receive RPC error reports when using call_with_confirmations()

Please enable RPC request-response logs on your node to see if the error message is actually transferred to Web3. If it is it should be part of the error object (if it's not then it might be some bug), but I'm assuming it isn't, hence it's a node issue.
