### ISSUE TITLE
rust-web3 cannot decode Infura getBlockByNumber response for pending block

### ISSUE THREAD

**Issue by e00E** [tomusdrw/rust-web3#483]
because Infura sets `miner` to null.

rust-web3 has a non optional author/miner field that defaults to the 0 address if the field is not present in the json:
https://github.com/tomusdrw/rust-web3/blob/5520ec249a011ea2e5de64417054bc3d2405db27/src/types/block.rs#L18

However when testing with Infura I found that they set `miner` to `null` which makes deserialization in rust-web3 fail. Potential solutions:

* make the rust field optional which would automatically handle missing and null
* see if there is a serde attribute (maybe from the serde_with crate) that also turns null into default
* do not make any change because Infura is returning a response that is invalid according to the ethrpc specification

**Comment by tomusdrw** [comment]
> see if there is a serde attribute (maybe from the serde_with crate) that also turns null into default

I like this one. Can we use `#[serde(deserialize_with = "path")]` for that?
