### ISSUE TITLE
Support calling through proxy contracts

### ISSUE THREAD

**Issue by ChosunOne** [tomusdrw/rust-web3#487]
Some contracts, such as the USDC token contract (https://etherscan.io/address/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48), use a proxy pattern where a call to the contract is delegated via a fallback function to another contract.  Currently attempting to follow this pattern results in an `invalid abi` error since the proxy contract abi itself does not match that of the proxied contract.  

Please consider supporting contract call-through via proxies or suggest a reasonable way of dealing with them.

**Comment by ChosunOne** [comment]
One way you could support this it to enable an optional map of abis to addresses, so that you can provide an abi for a specified delegated contract.

**Comment by ChosunOne** [comment]
An effective workaround is to edit the abi of the proxy contract to include that of the proxied contract.  While not idea, completely funcitonal.

**Comment by tomusdrw** [comment]
> An effective workaround is to edit the abi of the proxy contract to include that of the proxied contract. While not ideal, it's completely functional.

Why isn't this ideal? If the proxy contract supports the exact same interface that's the proper way of dealing with that AFAIK. Adding support for one specific proxy contract types (how would we even detect that from the ABI?) is not something I see a clear use case for.

**Comment by ChosunOne** [comment]
Agreed.  Closing the issue.
