### ISSUE TITLE
Build failed as error- no `sys` in the root

### ISSUE THREAD

**Issue by asmita-mf** [tomusdrw/rust-web3#493]
I am integrating web3 as depenedency in substrate-node-template(https://github.com/substrate-developer-hub/substrate-node-template)  inside pallet/template/cargo.toml.

Getting error as sys not defined. 
Can you explain why I am getting this. or how I can resolve

Complete Error is mentioned in gist: https://gist.github.com/asmita-mf/88f0fad70d7f56229bee431316f300e2

**Comment by tomusdrw** [comment]
You might need to compile with `wasm` feature for substrate. I'm not sure if the crate is compatible with `no-std` wasm though, never tested that.

**Comment by asmita-mf** [comment]
Hi
I have added as below.

In cargo.toml

[dependencies]
web3 = { version = "0.14.0",  optional = true }

[features]
default = ['std']
std = [
	'frame-support/std',
	'web3'
]
Sys error resolved but when I imported web3 in lib.rs as below
#![cfg_attr(not(feature = "std"), no_std)]

#[cfg(test)]
mod tests;

use web3::{
    contract::{Contract, Options},
    futures::{future, StreamExt},
    types:: {FilterBuilder, H160},
};

Getting error as web3 not defined.


Can you explain me why ?

I know may be this is silly question, but I am new to rust, so not getting exactly what is the reason. so please suggest me

**Comment by tomusdrw** [comment]
Substrate runtime is built without `std` feature. Please read on [cargo features](https://doc.rust-lang.org/cargo/reference/features.html).

In your example, you declare `web3` as optional dependency that is only included if `std` feature is enabled. Hence you are getting `web3` errors when `no_std` build is being done - cause the dependency is simply not there.

Also please ask Substrate-specific questions in appropriate channels, it isn't an issue with `web3` library at all.
