### ISSUE TITLE
Testing rust-web3 with Infura

### ISSUE THREAD

**Issue by fjrojas-ws** [tomusdrw/rust-web3#500]
I'm trying to publish an smartcontract in Infura using rust-web3, but because I have the private keys in the local side not in Infura, I use the method "sign_and_execute" thinking that rust-web3 could implement the transaction signature before calling infura, but actually that's not the way because it gives the following error;

`Error: Deployment(Api(Rpc(Error { code: ServerError(-32000), message: "Method personal_signTransaction not supported.", data: Some(Object({"name": String("Error"), "stack": String("Error: Method personal_signTransaction not supported.`

The deploy method call is;
`let contract = Contract::deploy(web3.eth(), include_bytes!("./res/SimpleStorage.abi"))?
        .confirmations(1)
        .poll_interval(time::Duration::from_secs(10))
        .options(Options::with(|opt| opt.gas = Some(3_000_000.into())))
        .sign_and_execute(bytecode, (), accounts[0], "123456")
        .await?;
`

Anybody can give me some clue to interact with Infura using rust-web3?
Thanks in advance.

**Comment by tomusdrw** [comment]
Please take a look at #391. AFAIR currently there is no way to deploy a contract, but sign the transaciton with a local keystore.
