### ISSUE TITLE
thread 'main' panicked at 'not currently running on a Tokio 0.2.x runtime.

### ISSUE THREAD

**Issue by japanesealexjones** [tomusdrw/rust-web3#501]
Hello all, I'm learning how to use Web3 and Rust. I'm trying to run the simple example found on the Readme, but getting the following error:

`thread 'main' panicked at 'not currently running on a Tokio 0.2.x runtime.', /mydir/tokio-0.2.25/src/runtime/handle.rs:118:28`

The code I'm using would be the following:

```
#[tokio::main]
async fn main() -> web3::Result<()> {
    let transport = web3::transports::Http::new("http://localhost:8545")?;
    let web3 = web3::Web3::new(transport);

    println!("Calling accounts.");
    let mut accounts = web3.eth().accounts().await?;
    println!("Accounts: {:?}", accounts);
    accounts.push("00a329c0648769a73afac7f9381e08fb43dbea72".parse().unwrap());

    println!("Calling balance.");
    for account in accounts {
        let balance = web3.eth().balance(account, None).await?;
        println!("Balance of {:?}: {}", account, balance);
    }

    Ok(())
}
```

I'll also share my Cargo.toml:
```
[dependencies]
web3 = "0.15.0"
tokio = { version = "1.0", features = ["full"] }
tokio-stream = { version = "0.1", optional = true }
tokio-util = { version = "0.6", optional = true, features = ["compat", "io"] }
```

Would anybody know how to fix this issue? Thanks!

**Comment by tomusdrw** [comment]
@japanesealexjones AFAICT the library refuses to work on `tokio=1.0` here, and we indeed require `tokio=0.2` in `web3=0.15.0`. Could you consider updating to `0.16.0` or changing `tokio` requirement to `0.2` in your `Cargo.toml` file?

**Comment by japanesealexjones** [comment]
> @japanesealexjones AFAICT the library refuses to work on `tokio=1.0` here, and we indeed require `tokio=0.2` in `web3=0.15.0`. Could you consider updating to `0.16.0` or changing `tokio` requirement to `0.2` in your `Cargo.toml` file?

That worked perfectly! Thanks @tomusdrw. 

One last question if you don't mind: I switched to Tokio 0.2 and still on web3 0.15.0. If Iupdate to 0.16.0. Would I still have to use Tokio 0.2?

**Comment by tomusdrw** [comment]
Honestly I'm not sure if `tokio=1.0` library will be able to run on `tokio=0.2` runtime. My guess is that with `0.16.0` it's better to upgrade to `tokio=1.0` everywhere, but if that's not feasible best to just try it out :) Please let us know how it went, cheers!
