### ISSUE TITLE
No method `sign_transaction` found

### ISSUE THREAD

**Issue by eute** [tomusdrw/rust-web3#510]
When I try to sign a transaction, I get the following error:

```rust
error[E0599]: no method named `sign_transaction` found for struct `Accounts<web3::transports::Either<Http, WebSocket>>` in the current scope
   --> src\main.rs:622:21
    |
622 |                 web3.accounts().sign_transaction(transaction_parameters, &seckey);
    |                                 ^^^^^^^^^^^^^^^^ method not found in `Accounts<web3::transports::Either<Http, WebSocket>>`
```

Any idea what could be causing this? it also seems like all other methods except `hash_message` documented at [https://docs.rs/web3/0.16.0/web3/api/struct.Accounts.html](https://docs.rs/web3/0.16.0/web3/api/struct.Accounts.html) return the same error.

**Comment by eute** [comment]
And again I have figured it out by looking into the source code. Noticed the `#[cfg(feature = "signing")]` line which unlocks the rest of the `Accounts` namespace. I've put the feature in my Cargo.toml and now it works.

This feature isn't mentioned in the "Cargo Features" section in README.md, however. This is especially critical for Windows users who have to compile with non-default features (without `ipc-tokio`), so I feel like it is important to state that in the documentation in case they want to sign transactions.

**Comment by tomusdrw** [comment]
Thanks for reporting! Addressed in https://github.com/tomusdrw/rust-web3/pull/511
