### ISSUE TITLE
Example of sending a transaction on actual Eth network (eg via Infura)

### ISSUE THREAD

**Issue by ilmoi** [tomusdrw/rust-web3#516]
I've managed to successfully send a transaction on ganache using [send_trandaction()](https://docs.rs/web3/0.16.0/web3/api/struct.Eth.html#method.send_transaction). However, the same method panics when trying  to do it on actual Ethereum via Infura. Which makes sense I guess since at no point did I use the private key or sign the transaction.

From [this thread](https://stackoverflow.com/questions/55154713/error-the-method-eth-sendtransaction-does-not-exist-is-not-available) I gather I need to use the raw transaction method instead. I also found [this crate](https://crates.io/crates/ethereum-tx-sign) to sign transactions. But so far I'm struggling to pull the lego pieces together - nor can I find examples in the docs (my bad if they're there and I missed them).

Could someone provide an example of how to send an actual eth transaction, or at the very least describe the order of methods I need to call?

**Comment by ilmoi** [comment]
Nevermind, found an answer in an older question [here](https://github.com/tomusdrw/rust-web3/issues/422).

For anyone with the same problem in the future:
1. create a `TransactionParameters` object (note: different to `TransactionRequest`)
```
    let tx_object = TransactionParameters {
        to: Some(to),
        value: U256::exp10(17), //0.1 eth
        ..Default::default()
    };
```
2. sign it with your private key
```
    let transport = web3::transports::Http::new(
        "https://rinkeby.infura.io/v3/ce0c2c5a809d408892888f67e83bf5e4",
    )?;
    let web3 = web3::Web3::new(transport);
    let signed = web3
        .accounts()
        .sign_transaction(tx_object, &prvk)
        .await
        .unwrap();
```
3. send to infura as raw transaction
```
    let r = web3
        .eth()
        .send_raw_transaction(signed.raw_transaction)
        .await
        .unwrap();
```

**Comment by tomusdrw** [comment]
@ilmoi thanks for sharing the solution. I'd be more than happy to accept the code as an example in `examples` directory. Would you be up for that?

**Comment by ilmoi** [comment]
On it.

**Comment by ilmoi** [comment]
Done - https://github.com/tomusdrw/rust-web3/pull/517

**Comment by ChudinovSE** [comment]
> Sorry for reopening this issue. But I got this error when using this sample. Could you help with updating the solution?
> 
> ![image](https://user-images.githubusercontent.com/37011495/165981115-9b7aa3a8-d383-4327-9416-1b752dffa9f2.png)

Check the version of secp256k1 in Cargo.toml, for this example must be secp256k1 = "0.21"

**Comment by Dark-wiz** [comment]
@ilmoi will this work when dealing with making a call to a smart contract?
I get this error when sending a transaction 
Api(Rpc(Error { code: ServerError(-32000), message: "unknown account", data: None })) 
<img width="1271" alt="Screenshot 2022-06-27 at 2 18 18 PM" src="https://user-images.githubusercontent.com/26813180/175930771-a21be1c5-0f1c-4bcc-a5d1-d3db8796c6a4.png">
