### ISSUE TITLE
How to find the correct hex value for topics to listen to events?

### ISSUE THREAD

**Issue by steadylearner** [tomusdrw/rust-web3#519]
I am following the example to listen to events and use their values.

I have problem to find the value for https://github.com/tomusdrw/rust-web3/blob/master/examples/contract_log_filter.rs#L34

I think d282f389399565f3671145f5916e51652b60eee8e5c759293a2f5771b8ddfd2e is some kind of hashed value of https://github.com/tomusdrw/rust-web3/blob/master/examples/contracts/SimpleEvent.sol#L4

When I test "Hello(address sender)" at https://emn178.github.io/online-tools/keccak_256.html I get this instead 3ea604711b30a47cd73d0cb5d7a543370b7ba988059e432d952d6d7f51f60f52

So, I think I have an issue finding a value to what to use here.

I want to test the event "event PairCreated(address indexed token0, address indexed token1, address pair, uint);" and not sure what value I should use for the topic.

I get c69bf9d5184aaeb9cc7770a2965c4fe78f50f7e347e3d1f6a329e329969a0167 with indexed token0,  indexed token1, pair etc and without them I get 165c77540a16c6415be9a14c8937f90e89ddc114ca9c8433f5ff16c8ab46b404

But, nothing seems to be working correctly. What can I use to find those values?

Can you give examples?

**Comment by tomusdrw** [comment]
They keyword to look for is Solidity Events and Log Topics relationship. For instance here: https://ethereum.stackexchange.com/questions/12950/what-are-solidity-events-and-how-they-are-related-to-topics-and-logs

**Comment by steadylearner** [comment]
Thanks for the link. I had to use uint256 (which is default for uint) instead of uint. 

So, I used "PairCreated(address,address,address,uint256)" instead to get the hash value and this time it worked.
