### ISSUE TITLE
Example showing how to deploy a new contract instance

### ISSUE THREAD

**Issue by casey** [tomusdrw/rust-web3#53]
Assuming that this is possible, an example showing how to deploy an instance of a new contract would be great. The example could assume that "solc" is installed on the system and shell out to it to compile the contract.

**Comment by casey** [comment]
Also, If you can give some hints for how to do it, I'd be happy to write such an example myself.

**Comment by tomusdrw** [comment]
Hi @casey, deploying a contract is as simple as sending transaction without a `recipient`.
You need a contract deployment bytecode (obtaining it is outside the scope of this library, you can use `solc` to do that) and you put it in `data` field of the transaction.

```rust
    let bytecode: Vec<u8> = "cafe123456789".parse().unwrap();
    let tx = web3::types::TransactionRequest {
      from: 5.into(),
      to: None,
      gas: Some(125.into()),
      gas_price: None,
      value: None,
      data: Some(bytecode.into()),
      nonce: None,
      condition: None,
    };
    let hash = web3.eth().send_transaction(tx).wait();
```

**Comment by casey** [comment]
I'm working on creating an example now, which I'll submit for inclusion once it's done.

One question, if the contract constructor takes a value, how is that value passed in the `TransactionRequest`?

**Comment by tomusdrw** [comment]
Hey! Seems that indeed its not yet possible without using `ethabi` externally.
I'll implement a convenience method to deploy a contract tomorrow - it will handle encoding of constructor parameters and sending a transaction.

Thanks for digging into this!

**Comment by casey** [comment]
Sweet, thank you!
