### ISSUE TITLE
How could I get an address from an address_str?

### ISSUE THREAD

**Issue by leeduckgo** [tomusdrw/rust-web3#538]
The example is not show yet.
I can get Addr from address_str:

```
let acct = hex!("f24ff3a9cf04c71dbc94d0b566f7a27b94566cac").into();
```

But I dont know how could I do the same thing with address:

```
let  addr = ???"0x4ad37B11C3C26C545e14247E9558fa7F156cFAC8"???
let contract = Contract::from_json(
    web3.eth(),
    addr,
    include_bytes!("../contracts/hello_world.json"),
)?;
```

**Comment by tomusdrw** [comment]
The `Address` type (which is just an alias for `H160`) implements [`FromStr`](https://docs.rs/web3/0.17.0/web3/types/struct.H160.html#impl-FromStr), which means that you can just do:
```
let addr: Address = "0x4ad37B11C3C26C545e14247E9558fa7F156cFAC8".parse();

**Comment by leeduckgo** [comment]
> The `Address` type (which is just an alias for `H160`) implements [`FromStr`](https://docs.rs/web3/0.17.0/web3/types/struct.H160.html#impl-FromStr), which means that you can just do:
> 
> ```
> let addr: Address = "0x4ad37B11C3C26C545e14247E9558fa7F156cFAC8".parse().unwrap();
> ```

thx a lot!
