### ISSUE TITLE
Account creation

### ISSUE THREAD

**Issue by io12** [tomusdrw/rust-web3#540]
There are some functions in the [`web3.eth.accounts`](https://web3js.readthedocs.io/en/v1.4.0/web3-eth-accounts.html#web3-eth-accounts) namespace of web3.js that could be useful in rust-web3 for account creation. For example, `create` and `privateKeyToAccount`.

**Comment by tomusdrw** [comment]
@io12 PRs welcome! It's also possible to extend `Web3` with custom `Namespace` implementations (see [here](https://github.com/tomusdrw/rust-web3/blob/master/src/api/mod.rs#L66)).

**Comment by io12** [comment]
Oh, apparently `create` is `secp256k1::SecretKey::new` and `privateKeyToAccount` is `signing::secret_key_address`.

**Comment by io12** [comment]
> Is there any way to recover an account from mnemonic words as the web3js does?
@songtianyi It looks like the [bip32](https://docs.rs/bip32/latest/bip32/index.html) crate can do this, but I haven't tried it.

**Comment by songtianyi** [comment]
> > Is there any way to recover an account from mnemonic words as the web3js does?
> 
> @songtianyi It looks like the [bip32](https://docs.rs/bip32/latest/bip32/index.html) crate can do this, but I haven't tried it.

the  bip32 [doc](https://docs.rs/bip32/latest/bip32/) says 
```
[Limitations and further work](https://docs.rs/bip32/latest/bip32/#limitations-and-further-work)
Only 24-word BIP39 mnemonics are supported
BIP43, BIP44, BIP49, BIP84 not yet properly supported
```
