### ISSUE TITLE
error: failed to run custom build command for `secp256k1-sys v0.4.1`

### ISSUE THREAD

**Issue by weishengbin** [tomusdrw/rust-web3#543]
Build an error:

error: failed to run custom build command for `secp256k1-sys v0.4.1`

My computer is MacOS

**Comment by tomusdrw** [comment]
@weishengbin please take a look at the requirements of `secp256k1-sys`, perhaps it doesn't compile on M1 (are you on M1?)?

If you don't need TLS (https/wss) support, you can also consider disabling `default-features=false` and compiling without that dependency.

Would you also mind posting full compilation log and the details of the error message?

**Comment by weishengbin** [comment]
> @weishengbin please take a look at the requirements of `secp256k1-sys`, perhaps it doesn't compile on M1 (are you on M1?)?
> 
> If you don't need TLS (https/wss) support, you can also consider disabling `default-features=false` and compiling without that dependency.
> 
> Would you also mind posting full compilation log and the details of the error message?

`   Compiling num-traits v0.2.14
   Compiling num-integer v0.1.44
   Compiling openssl-sys v0.9.66
   Compiling secp256k1-sys v0.4.1
   Compiling tokio-macros v1.3.0
   Compiling impl-trait-for-tuples v0.2.1
   Compiling url v2.2.2
   Compiling pin-project-internal v1.0.8
error: failed to run custom build command for `secp256k1-sys v0.4.1`

Caused by:
  process didn't exit successfully: `/Users/mac/bingo/_project_rust/rust-web3/target/release/build/secp256k1-sys-330c6ec6714ae9b1/build-script-build` (exit status: 1)
  --- stdout
  TARGET = Some("x86_64-unknown-linux-musl")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-apple-darwin")
  CC_x86_64-unknown-linux-musl = None
  CC_x86_64_unknown_linux_musl = None
  TARGET_CC = None
  CC = None
  CROSS_COMPILE = None
  CFLAGS_x86_64-unknown-linux-musl = None
  CFLAGS_x86_64_unknown_linux_musl = None
  TARGET_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  CC_x86_64-unknown-linux-musl = None
  CC_x86_64_unknown_linux_musl = None
  TARGET_CC = None
  CC = None
  CROSS_COMPILE = None
  CFLAGS_x86_64-unknown-linux-musl = None
  CFLAGS_x86_64_unknown_linux_musl = None
  TARGET_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "musl-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "depend/secp256k1/" "-I" "depend/secp256k1/include" "-I" "depend/secp256k1/src" "-Wall" "-Wextra" "-DSECP256K1_BUILD=1" "-DSECP256K1_API=" "-DENABLE_MODULE_ECDH=1" "-DENABLE_MODULE_SCHNORRSIG=1" "-DENABLE_MODULE_EXTRAKEYS=1" "-DECMULT_GEN_PREC_BITS=4" "-DUSE_NUM_NONE=1" "-DUSE_FIELD_INV_BUILTIN=1" "-DUSE_SCALAR_INV_BUILTIN=1" "-DECMULT_WINDOW_SIZE=15" "-DUSE_EXTERNAL_DEFAULT_CALLBACKS=1" "-DENABLE_MODULE_RECOVERY=1" "-o" "/Users/mac/bingo/_project_rust/rust-web3/target/x86_64-unknown-linux-musl/release/build/secp256k1-sys-888ee02e3c3da06e/out/depend/secp256k1/contrib/lax_der_parsing.o" "-c" "depend/secp256k1/contrib/lax_der_parsing.c"

  --- stderr


  error occurred: Failed to find tool. Is `musl-gcc` installed?


warning: build failed, waiting for other jobs to finish...
error: build failed`

**Comment by tomusdrw** [comment]
@weishengbin can you try installing `musl-gcc` or compiling without TLS?

**Comment by tomusdrw** [comment]
Closing, since I assume this is not an `rust-web3` issue.

**Comment by pifragile** [comment]
@weishengbin  did you solve this? i get the same error in a different context. i am also on macos with a i9.

**Comment by arik-so** [comment]
Hi there, any luck? I'm also running into this issue. One solution has been to run `sudo xcode-select --switch /Library/Developer/CommandLineTools`, but that breaks cargo lipo, so I'm looking for something more reliable.

**Comment by hcheng826** [comment]
@weishengbin did you get this fixed in the end? I have the same issue 🥲

**Comment by Bonnai2112** [comment]
Same error too @weishengbin , some news ?

**Comment by divyanshvn** [comment]
"adding AR=llvm" before cargo fixed it for me, although the error I received had " Is `aarch64-linux-android-ar` installed? " at the end

**Comment by msapple0338** [comment]
Now I`m too with the same error, Please anyone help me.
============error log
   Compiling futures-channel v0.3.28
   Compiling bitcoin_hashes v0.3.2
error: failed to run custom build command for `secp256k1-sys v0.4.2`

**Comment by emlanis** [comment]
I'm looking for a solution to this as well.

**Comment by maoueh** [comment]
On OSX, at least at time of writing, the default `clang` compiler provided by Apple does not contain the necessary support to target `wasm32-unknown-unknown`.

You can install a version from `brew` instead that has the support for it, here how I solve such compilation issue:

```
brew install llvm
export PATH="/opt/homebrew/opt/llvm/bin:$PATH" &&  export LDFLAGS="-L/opt/homebrew/opt/llvm/lib" && export CPPFLAGS="-I/opt/homebrew/opt/llvm/include"
cargo build --target wasm32-unknown-unknown --release
```
