### ISSUE TITLE
Converting U256 little indian to decimal places

### ISSUE THREAD

**Issue by Corfucinas** [tomusdrw/rust-web3#550]
Hi, I'm currently learning the modules of this library and wrote a simple script to calculate the total balance of a token when it is bridged to Polygon.

```rust
let total_locked_on_ethereum_bridge: U256 = token_contract_ethereum
        .query(
            "balanceOf",
            H160::from_str(TOKENS_LOCKED_ON_ETHEREUM_BRIDGE).unwrap(),
            None,
            Options::default(),
            None,
        )
        .await
        .unwrap();
```

This returns a U256 `2105292267225401350711477`, how can I get the decimal representation with decimal places?

**Comment by tomusdrw** [comment]
Hey!

This is a decimal representation but in WEIs (Ethereum's lowest denominator). To obtain ETH value, you need to divide it by `10**18`.

```
2105292267225401350711477 / 10**18 = 2_105_292 ETH
```
does that look about right?

**Comment by Corfucinas** [comment]
> Hey!
> 
> This is a decimal representation but in WEIs (Ethereum's lowest denominator). To obtain ETH value, you need to divide it by `10**18`.
> 
> ```
> 2105292267225401350711477 / 10**18 = 2_105_292 ETH
> ```
> does that look about right?
> 

Yeah that works, I got confused by not finding this method. Usually it is on other web3 libraries and saves you from writing it yourself.

Thanks for the quick reply!

**Comment by lu-zero** [comment]
Would be acceptable adding those shorthands?

**Comment by Corfucinas** [comment]
I used something like this (needed the output for an HTML page)
```rust
use num_format::{CustomFormat, Grouping, Locale, ToFormattedString};

let num_format = CustomFormat::builder()
        .grouping(Grouping::Standard)
        .separator("")
        .build()
        .unwrap();

let convert_wei_to_decimal = |bignumber: U256| -> DecimalNumber {
        (bignumber.as_u128() / u128::pow(10, 18)).to_formatted_string(&num_format)
    };
```

In case it is handy for anyone
