### ISSUE TITLE
Doesn't compile on Windows

### ISSUE THREAD

**Issue by evergreen-trading-systems** [tomusdrw/rust-web3#557]
Are you familiar with

![image](https://user-images.githubusercontent.com/4870868/137587618-8548b36a-f754-4454-ba26-1faa72404108.png)

**Comment by evergreen-trading-systems** [comment]
Are there certain libraries that could cause conflicts e.g. `mysql_async`

**Comment by tomusdrw** [comment]
Closing, since the issue seems to be an outdated compiler.
