### ISSUE TITLE
websocket infura secret support

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [tomusdrw/rust-web3#567]
I'm not too clued up on websockets and authentication. Is it currently possible to utilise websockets along with password / username? 

Creating a websocket currently takes in just `url: &str` which doesn't allow setting a username and password.

**Comment by tomusdrw** [comment]
Would `wss://username:password@host/` work? If not we can easily add authorisation header support (AFAICT Infura is using basic auth).

**Comment by Mirko-von-Leipzig** [comment]
`wss://username:password@host/` gets rejected -- unless I'm doing it wrong: `wss://:<secret>@host` (since there is no username)? This form gets rejected.

The example given in the docs is:
`wscat -c wss://mainnet.infura.io/ws/v3/YOUR-PROJECT-ID --auth ":YOUR-PROJECT-SECRET"`
