### ISSUE TITLE
Why the Address type is H160? How should I convert from a &str?

### ISSUE THREAD

**Issue by hzqd** [tomusdrw/rust-web3#607]
I try to convert a `&str` address to `Address` type using `Address::from_slice(<&str>.as_bytes())`.

Getting panic message:
``` none 
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `42`,
 right: `20`'
```
How should I convert a `&str` to an `Address`?

**Comment by tomusdrw** [comment]
`H160` implements `FromStr` trait ([here](https://docs.rs/web3/latest/web3/types/struct.H160.html#impl-FromStr)), so you can simply do:
```rust
let str_addr: &str = "...";
let addr: Address = str_addr.parse().unwrap()
```
