### ISSUE TITLE
How can I use it with dynamic linking?

### ISSUE THREAD

**Issue by usd-yamazaki** [tomusdrw/rust-web3#61]
Since this library is an LGPL license, I would like to use it with dynamic linking.
How can I do dynamic linking?
Thank you.

**Comment by debris** [comment]
fork the library and change `crate-type` to `dylib` or `cdylib`. [docs](http://doc.crates.io/manifest.html#building-dynamic-or-static-libraries)

**Comment by usd-yamazaki** [comment]
thank you for your answer.
I tried and succeeded in the following way.

- Added dylib setting to rust-web3/Cargo.toml
```
[lib]
name = "web3"
crate-type = ["dylib"]
```

- Added export function to rust-web3/src/lib.rs
```
use types::Address;
use types::U256;
#[no_mangle]
pub extern "C" fn get_balance(address: Address) -> U256 {
    let (_eloop, http) = transports::Http::new("http://localhost:8545").unwrap();
    let rpc = Web3::new(&http);
    rpc.eth().balance(address, None).wait().unwrap()
}
```

- Create a calling program
```
extern crate libloading;

struct Address([u8; 20]);
#[derive(Debug)]
struct U256([u8; 32]);

fn main() {
    let dylib = libloading::Library::new("rust-web3/target/release/web3.dll");
    match dylib {
        Ok(lib) => {
            let func: Result<libloading::Symbol<extern "C" fn(Address) -> U256>, _> =
                unsafe { lib.get(b"get_balance") };
            match func {
                Ok(get_balance) => {
                    let address = Address([0x00, 0xC9, 0xE6, 0x5a, 0x50, 0x41, 0xe2, 0x2e, 0x87,
                                           0x85, 0x3e, 0xf8, 0xAc, 0xff, 0x2E, 0x0a, 0x16, 0xc4,
                                           0x07, 0x5c]);
                    println!("{:?}", get_balance(address))
                }
                Err(msg) => println!("{:?}", msg),
            }
        }
        Err(msg) => println!("{:?}", msg),
    }
}
```

However, in this case, it seems to be very wasteful as we have to prepare a large number of export functions.
As far as I looked, Rust and LGPL license don't go along well.
Would you consider changing the license type from LGPL to MIT?

Thank you.

**Comment by usd-yamazaki** [comment]
I referred to here.
https://internals.rust-lang.org/t/cargo-build-certain-dependencies-as-dylibs/4586

**Comment by usd-yamazaki** [comment]
I appreciate the wonderful action!
