### ISSUE TITLE
failed to resolve: use of undeclared crate or module `secp256k1`

### ISSUE THREAD

**Issue by peter-jim** [tomusdrw/rust-web3#641]
when I use rust-web3 to my project .  I cant import secp256k1. but Cargo.toml is work.

[dependencies]
secp256k1 = { version = "0.22.1", features = ["recovery"], optional = true }
once_cell = { version = "1.8.0", optional = true }

----
use secp256k1::key::SecretKey;

show error
failed to resolve: use of undeclared crate or module `secp256k1`
use of undeclared crate or module `secp256k1`rustc[E0433](https://doc.rust-lang.org/error-index.html#E0433)

**Comment by palinko91** [comment]
For me the transakction signing works with older crates only. Try
web3 = "=0.17.0"
secp256k1 = "=0.20.3"

**Comment by peter-jim** [comment]
thanks, I solved the problem.
