### ISSUE TITLE
testrpc runtime error: Stack underflow in Contract example

### ISSUE THREAD

**Issue by alanpoon** [tomusdrw/rust-web3#70]
I could deploy contracts using truffle in testrpc without problem.

**Comment by tomusdrw** [comment]
Do you mean this example: https://github.com/tomusdrw/rust-web3/blob/master/examples/contract.rs#L13 ?
The bytecode there is not a real one. Might be good to have a correct example there, indeed.

**Comment by alanpoon** [comment]
yes
