### ISSUE TITLE
Issue with IPC transport?

### ISSUE THREAD

**Issue by malzzz** [tomusdrw/rust-web3#83]
I am very new to Rust, so there might be something that I'm overlooking; however, I was implementing some Parity-specific methods in a separate fork, and while benchmarking with [criterion.rs](https://github.com/japaric/criterion.rs), I noticed that method calls to `parity_pendingTransactions` stalled indefinitely over IPC.  This method works 100% of the time with the http transport, so I am assuming the problem isn't with my implementation.  

At first I thought it was due to the size of the RPC return (this was when there were around 15k+ pending), but that doesn't quite make sense, since a 20MB buffered transfer shouldn't be an issue over a unix socket.

This issue did make me recall a problem I was having a while back in Java/Scala.  We have a microservice that would often stall when polling our Parity node via IPC with the Web3j Java client.  We then re-wrote that service from the ground-up in Scala with our own IPC implementation, but still had the same issue.  We then switched all calls to http and everything was fine.

So, considering that there might be an issue with IPC calls across three different implementations, in three different languages, and since you work on Parity as well, we wanted to solicit your advice on where you think the issue might reside?

P.S.: You mentioned in another post that you have no issues getting 20k calls/sec using the rust-web3 client.  Would you mind sharing the hardware specs used to achieve that?  Thanks!

**Comment by tomusdrw** [comment]
Hey @antikantian sorry to reply so late.

So it sounds like a possible issue with Parity server implementation then, x-posted the issue to https://github.com/paritytech/jsonrpc/ repo.

You can run benchmarks with `cargo run --release --example bench`. My results:
```
[http] 1191 reqs/s (100000 reqs in 83909 ms)
[http] 1179 reqs/s (99999 reqs in 84812 ms)
[ ipc] 48661 reqs/s (100000 reqs in 2055 ms)
[ ipc] 58926 reqs/s (99999 reqs in 1697 ms)
```

(note it only fetches latest block number, so it's fairly cheap for Parity and not much data to serialize, things might be completely different with `parity_pendingTransactions`)

**Comment by antikantian** [comment]
Hi @tomusdrw, np.  Ah, I figured as much; I'll have a look at the jsonrpc repo.  

It's interesting that your benchmarks show a large discrepancy between http and ipc.  Here are my results:

<img width="318" alt="parity_rpc" src="https://user-images.githubusercontent.com/16178586/36035693-aa4d3f10-0d85-11e8-9acb-fa9cb45d0bf9.png">

**Comment by tomusdrw** [comment]
I run the tests on oldish Parity version (1.7.13-stable) - it didn't have the new multi-threaded HTTP server. Updater results are closer to yours:
```
cargo run --example bench --release
    Finished release [optimized] target(s) in 0.0 secs
     Running `target/release/examples/bench`
[http] 30778 reqs/s (100000 reqs in 3249 ms)
[http] 29290 reqs/s (99999 reqs in 3414 ms)
[ ipc] 48285 reqs/s (100000 reqs in 2071 ms)
[ ipc] 52825 reqs/s (99999 reqs in 1893 ms)
```

**Comment by tomusdrw** [comment]
Seems that the issue is resolved here, please reopen if there is anything more to address.
