### ISSUE TITLE
Need an example of how to wait for confirmations

### ISSUE THREAD

**Issue by akuanti** [tomusdrw/rust-web3#89]
I would like to be able to call a function on a contract, wait until the transaction is confirmed, and then do something with the result. I have a feeling this is relatively straight-forward, but the documentation isn't clear.

There is `wait_for_confirmations` and `send_transaction_with_confirmation`, but neither of these are part of the contract interface, and  I'm not sure what I should be passing to these. A simple example would be much appreciated.

**Comment by tomusdrw** [comment]
See #102 and #103 thread
