### ISSUE TITLE
Receipt should include status field

### ISSUE THREAD

**Issue by akuanti** [tomusdrw/rust-web3#97]
The current version of JSON RPC includes the following for [`eth_getTransactionReceipt`](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_gettransactionreceipt)

> It also returns either :
>
> `root` :` DATA` 32 bytes of post-transaction stateroot (pre Byzantium)
> `status`: `QUANTITY` either 1 (success) or 0 (failure)

The `Receipt` struct does not include either of these fields.

**Comment by tomusdrw** [comment]
Resolved via #98
